import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

/**
 * confirm-visit Edge Function
 * 
 * Creates a patient visit and generates a token number:
 * 1. Validates patient_id and clinic_id
 * 2. Creates visit record (token auto-generated by DB trigger)
 * 3. Returns visit_id and token_number
 * 
 * Public endpoint for QR self-intake
 */
serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    const { patient_id, clinic_id, visit_type, chief_complaint } = await req.json();

    // ── Validation ──
    if (!patient_id) {
      return new Response(JSON.stringify({ error: "patient_id is required" }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    if (!clinic_id) {
      return new Response(JSON.stringify({ error: "clinic_id is required" }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // ── Verify patient belongs to clinic ──
    const { data: patient, error: pErr } = await supabase
      .from("patients")
      .select("id, clinic_id")
      .eq("id", patient_id)
      .eq("clinic_id", clinic_id)
      .single();

    if (pErr || !patient) {
      return new Response(JSON.stringify({ error: "Patient not found in this clinic" }), {
        status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // ── Check for duplicate same-day visit ──
    const today = new Date().toISOString().split("T")[0];
    const { data: existingVisit } = await supabase
      .from("patient_visits")
      .select("id, token_number, status")
      .eq("patient_id", patient_id)
      .eq("clinic_id", clinic_id)
      .eq("visit_date", today)
      .not("status", "eq", "completed")
      .maybeSingle();

    if (existingVisit) {
      // Return existing active visit instead of creating duplicate
      return new Response(JSON.stringify({
        visit_id: existingVisit.id,
        token_number: existingVisit.token_number,
        status: existingVisit.status,
        duplicate: true,
      }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // ── Create visit (token generated by DB trigger) ──
    const { data: visit, error: vErr } = await supabase
      .from("patient_visits")
      .insert({
        patient_id,
        clinic_id,
        visit_type: visit_type || "qr-walkin",
        status: "registered",
        chief_complaint: typeof chief_complaint === "string" ? chief_complaint.slice(0, 500) : "",
      })
      .select("id, token_number, status, visit_token")
      .single();

    if (vErr) throw new Error(`Visit creation failed: ${vErr.message}`);

    // ── Audit ──
    supabase.from("audit_logs").insert({
      actor_id: patient_id, // self-registered
      clinic_id,
      event_type: "visit_registered",
      target_type: "patient_visit",
      target_id: visit.id,
      metadata: { visit_type: visit_type || "qr-walkin", token_number: visit.token_number },
    }).then(() => {});

    return new Response(JSON.stringify({
      visit_id: visit.id,
      visit_token: visit.visit_token,
      token_number: visit.token_number,
      status: visit.status,
      duplicate: false,
    }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("confirm-visit error:", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
