import { Bot, Info } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";

interface AiDisclosureBadgeProps {
  /** Short label shown on the badge */
  label?: string;
  /** Detailed explanation shown in tooltip */
  tooltip?: string;
  /** Visual variant */
  variant?: "inline" | "block";
  className?: string;
}

export default function AiDisclosureBadge({
  label = "AI-Assisted Draft",
  tooltip = "This content was generated by AI and reviewed by your doctor. AI assists with structuring — your doctor makes all clinical decisions.",
  variant = "inline",
  className = "",
}: AiDisclosureBadgeProps) {
  if (variant === "block") {
    return (
      <div className={`flex items-start gap-2 rounded-lg border border-primary/20 bg-primary/5 px-3 py-2 ${className}`}>
        <Bot className="h-4 w-4 text-primary mt-0.5 shrink-0" />
        <div>
          <p className="text-xs font-medium text-primary">{label}</p>
          <p className="text-[11px] text-muted-foreground mt-0.5">{tooltip}</p>
        </div>
      </div>
    );
  }

  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <Badge variant="outline" className={`gap-1 text-[10px] border-primary/30 text-primary cursor-help ${className}`}>
            <Bot className="h-3 w-3" />
            {label}
            <Info className="h-2.5 w-2.5 opacity-60" />
          </Badge>
        </TooltipTrigger>
        <TooltipContent side="bottom" className="max-w-xs text-xs">
          {tooltip}
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
}
