import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// ─── PHYSIOLOGY STATE DEFINITIONS ───
// [state_name, description, organ_system]
type PhysioState = [string, string, string];

function generatePhysiologyStates(): PhysioState[] {
  return [
    // ── RESPIRATORY (25) ──
    ["airway inflammation", "inflammatory response in bronchial and tracheal mucosa causing edema and mucus hypersecretion", "respiratory"],
    ["bronchoconstriction", "smooth muscle contraction of bronchial walls reducing airway caliber", "respiratory"],
    ["alveolar damage", "disruption of alveolar epithelial-endothelial barrier impairing gas exchange", "respiratory"],
    ["bronchial hyperreactivity", "exaggerated bronchoconstrictor response to stimuli in sensitized airways", "respiratory"],
    ["mucus hypersecretion", "excessive production of mucus by goblet cells and submucosal glands", "respiratory"],
    ["pulmonary vascular congestion", "increased hydrostatic pressure in pulmonary capillaries causing fluid transudation", "respiratory"],
    ["airway obstruction", "mechanical or functional narrowing of airways impeding airflow", "respiratory"],
    ["pharyngeal inflammation", "inflammation of pharyngeal mucosa with edema and erythema", "respiratory"],
    ["nasal mucosal inflammation", "edema and increased secretions of nasal mucosa from allergic or infectious triggers", "respiratory"],
    ["pleural inflammation", "irritation and inflammation of pleural membranes causing effusion or friction", "respiratory"],
    ["pulmonary fibrosis", "progressive replacement of functional lung tissue with fibrotic tissue", "respiratory"],
    ["ventilation-perfusion mismatch", "imbalance between alveolar ventilation and pulmonary blood flow", "respiratory"],
    ["respiratory muscle fatigue", "exhaustion of diaphragm and intercostal muscles from increased work of breathing", "respiratory"],
    ["upper airway edema", "swelling of supraglottic and glottic structures compromising airway patency", "respiratory"],
    ["pulmonary hypertension", "elevated pressure in pulmonary arterial system increasing right heart workload", "respiratory"],
    ["atelectasis", "collapse of lung parenchyma with loss of volume and impaired gas exchange", "respiratory"],
    ["laryngeal inflammation", "inflammation of laryngeal mucosa causing hoarseness and stridor", "respiratory"],
    ["sinusoidal mucosal inflammation", "inflammation and edema of paranasal sinus mucosa obstructing ostia", "respiratory"],
    ["pulmonary parenchymal necrosis", "tissue death within lung parenchyma from infection or infarction", "respiratory"],
    ["ciliary dysfunction", "impaired mucociliary clearance predisposing to infection and mucus retention", "respiratory"],
    ["surfactant deficiency", "reduced surfactant production causing alveolar collapse and respiratory distress", "respiratory"],
    ["bronchiolar destruction", "chronic destruction of small airways leading to air trapping", "respiratory"],
    ["pulmonary edema", "accumulation of fluid in alveolar spaces impairing oxygenation", "respiratory"],
    ["pneumothorax physiology", "air entry into pleural space causing lung collapse and mediastinal shift", "respiratory"],
    ["hypoxemic respiratory failure", "inability to maintain adequate arterial oxygen tension", "respiratory"],

    // ── CARDIOVASCULAR (25) ──
    ["myocardial ischemia", "reduced blood supply to cardiac muscle resulting in oxygen deprivation", "cardiovascular"],
    ["myocardial necrosis", "irreversible death of cardiac myocytes from prolonged ischemia", "cardiovascular"],
    ["cardiac arrhythmia", "abnormal electrical conduction causing irregular heart rhythm", "cardiovascular"],
    ["left ventricular systolic dysfunction", "impaired contractility of left ventricle reducing cardiac output", "cardiovascular"],
    ["left ventricular diastolic dysfunction", "impaired relaxation and filling of left ventricle", "cardiovascular"],
    ["vascular endothelial dysfunction", "impaired nitric oxide-mediated vasodilation and prothrombotic state", "cardiovascular"],
    ["atherosclerotic plaque formation", "lipid deposition and inflammatory remodeling of arterial intima", "cardiovascular"],
    ["increased systemic vascular resistance", "elevated arterial resistance from arteriolar constriction", "cardiovascular"],
    ["venous thrombosis", "formation of blood clot within venous system obstructing blood flow", "cardiovascular"],
    ["cardiac valve dysfunction", "impaired opening or closing of cardiac valves disrupting blood flow", "cardiovascular"],
    ["pericardial inflammation", "inflammation of pericardium causing friction, effusion, or constriction", "cardiovascular"],
    ["cardiac conduction block", "disruption of electrical signal propagation through cardiac conduction system", "cardiovascular"],
    ["aortic wall degeneration", "weakening of aortic media leading to aneurysm or dissection", "cardiovascular"],
    ["peripheral vascular insufficiency", "inadequate arterial blood supply to extremities", "cardiovascular"],
    ["venous valve incompetence", "failure of venous valves allowing retrograde blood flow", "cardiovascular"],
    ["cardiac tamponade physiology", "compression of cardiac chambers by pericardial fluid restricting filling", "cardiovascular"],
    ["right heart failure", "impaired right ventricular function with systemic venous congestion", "cardiovascular"],
    ["coronary vasospasm", "transient narrowing of coronary artery from smooth muscle spasm", "cardiovascular"],
    ["myocardial inflammation", "inflammatory infiltration of myocardium with edema and necrosis", "cardiovascular"],
    ["baroreceptor dysfunction", "impaired arterial baroreceptor sensitivity affecting blood pressure regulation", "cardiovascular"],
    ["cardiac output reduction", "decreased volume of blood pumped per minute by the heart", "cardiovascular"],
    ["fluid overload", "excessive intravascular volume causing edema and congestion", "cardiovascular"],
    ["systemic hypoperfusion", "global reduction in tissue perfusion causing organ dysfunction", "cardiovascular"],
    ["vasodilatory shock", "pathological systemic vasodilation causing distributive shock", "cardiovascular"],
    ["microvascular thrombosis", "formation of microthrombi in small vessels causing organ ischemia", "cardiovascular"],

    // ── NEUROLOGICAL (25) ──
    ["neuroinflammation", "inflammatory response within central nervous system with glial activation", "neurological"],
    ["meningeal irritation", "inflammation or irritation of meninges causing headache and neck stiffness", "neurological"],
    ["cortical spreading depression", "wave of neuronal depolarization followed by suppression causing aura", "neurological"],
    ["cerebral ischemia", "reduced blood flow to brain tissue causing neuronal injury", "neurological"],
    ["intracranial pressure elevation", "increased pressure within cranial vault from mass effect or CSF obstruction", "neurological"],
    ["demyelination", "destruction of myelin sheath disrupting nerve signal transmission", "neurological"],
    ["peripheral nerve compression", "mechanical compression of peripheral nerves causing pain and dysfunction", "neurological"],
    ["neuromuscular junction dysfunction", "impaired transmission at neuromuscular junction", "neurological"],
    ["dopaminergic depletion", "reduced dopamine neurotransmitter levels in basal ganglia", "neurological"],
    ["seizure activity", "abnormal excessive synchronized neuronal discharge", "neurological"],
    ["cerebral hemorrhage", "bleeding into brain parenchyma or subarachnoid space", "neurological"],
    ["peripheral neuropathy", "damage to peripheral nerves causing sensory or motor deficits", "neurological"],
    ["central sensitization", "amplified pain processing in central nervous system", "neurological"],
    ["trigeminal nerve irritation", "irritation of trigeminal nerve branches causing facial pain", "neurological"],
    ["facial nerve paralysis", "disruption of facial nerve function causing ipsilateral weakness", "neurological"],
    ["vestibular dysfunction", "impaired vestibular apparatus function causing vertigo", "neurological"],
    ["cholinergic deficit", "reduced acetylcholine neurotransmission in cerebral cortex", "neurological"],
    ["ascending paralysis", "progressive weakness ascending from lower to upper extremities", "neurological"],
    ["spinal cord compression", "mechanical compression of spinal cord causing myelopathy", "neurological"],
    ["autonomic dysregulation", "impaired sympathetic and parasympathetic nervous system balance", "neurological"],
    ["neurotoxicity", "direct toxic damage to neural tissue from exogenous agents", "neurological"],
    ["blood-brain barrier disruption", "breakdown of blood-brain barrier allowing pathogen and protein entry", "neurological"],
    ["cerebral vasospasm", "narrowing of cerebral arteries following subarachnoid hemorrhage", "neurological"],
    ["neurodegenerative protein aggregation", "accumulation of misfolded proteins causing progressive neuronal death", "neurological"],
    ["nerve root compression", "compression of spinal nerve roots causing radiculopathy", "neurological"],

    // ── GASTROINTESTINAL (25) ──
    ["gastric mucosal erosion", "disruption of gastric mucosal barrier by acid or NSAIDs", "gastrointestinal"],
    ["intestinal inflammation", "inflammatory infiltration of intestinal wall from infection or autoimmunity", "gastrointestinal"],
    ["hepatocellular injury", "damage to hepatocytes from toxins, viruses, or ischemia", "gastrointestinal"],
    ["biliary obstruction", "blockage of bile ducts causing cholestasis and jaundice", "gastrointestinal"],
    ["pancreatic acinar cell injury", "autodigestion of pancreatic tissue by premature enzyme activation", "gastrointestinal"],
    ["intestinal motility dysfunction", "disordered peristalsis causing altered bowel transit", "gastrointestinal"],
    ["gastroesophageal reflux", "retrograde flow of gastric contents into esophagus causing mucosal injury", "gastrointestinal"],
    ["peritoneal irritation", "inflammation of peritoneum causing localized or generalized abdominal pain", "gastrointestinal"],
    ["intestinal barrier disruption", "increased permeability of intestinal epithelium", "gastrointestinal"],
    ["hepatic fibrosis", "progressive scarring of liver parenchyma replacing functional tissue", "gastrointestinal"],
    ["portal hypertension", "elevated pressure in portal venous system due to hepatic resistance", "gastrointestinal"],
    ["visceral hypersensitivity", "enhanced perception of normal intestinal stimuli as painful", "gastrointestinal"],
    ["malabsorption", "impaired nutrient absorption due to mucosal damage or enzyme deficiency", "gastrointestinal"],
    ["intestinal obstruction", "mechanical or functional blockage preventing normal bowel transit", "gastrointestinal"],
    ["gallbladder inflammation", "inflammation of gallbladder wall from stone impaction or infection", "gastrointestinal"],
    ["colonic mucosal ulceration", "ulcerative destruction of colonic mucosa with bleeding", "gastrointestinal"],
    ["appendiceal obstruction", "blockage of appendiceal lumen leading to distension and inflammation", "gastrointestinal"],
    ["diverticular inflammation", "inflammation of colonic diverticula from microperforation", "gastrointestinal"],
    ["helicobacter pylori infection", "chronic gastric infection causing mucosal damage and ulceration", "gastrointestinal"],
    ["hepatic encephalopathy", "cerebral dysfunction from liver failure and ammonia accumulation", "gastrointestinal"],
    ["gastrointestinal hemorrhage", "bleeding from upper or lower gastrointestinal tract", "gastrointestinal"],
    ["esophageal dysmotility", "impaired esophageal peristalsis causing dysphagia", "gastrointestinal"],
    ["bacterial overgrowth", "excessive bacterial colonization of small intestine", "gastrointestinal"],
    ["colonic dysmotility", "disordered colonic motility causing constipation or diarrhea", "gastrointestinal"],
    ["mesenteric ischemia", "reduced blood supply to intestinal mesentery causing bowel necrosis", "gastrointestinal"],

    // ── ENDOCRINE (20) ──
    ["insulin resistance", "reduced cellular responsiveness to insulin causing hyperglycemia", "endocrine"],
    ["insulin deficiency", "absolute or relative lack of insulin production by pancreatic beta cells", "endocrine"],
    ["thyroid hormone deficiency", "reduced production of T3 and T4 causing hypometabolic state", "endocrine"],
    ["thyroid hormone excess", "overproduction of thyroid hormones causing hypermetabolic state", "endocrine"],
    ["cortisol excess", "chronically elevated cortisol levels causing metabolic and immune disruption", "endocrine"],
    ["cortisol deficiency", "inadequate cortisol production causing adrenal crisis risk", "endocrine"],
    ["hyperandrogenism", "excess androgen production causing hirsutism and acne", "endocrine"],
    ["diabetic ketoacidosis physiology", "absolute insulin deficiency causing ketone body accumulation and acidosis", "endocrine"],
    ["hyperosmolar state", "severe hyperglycemia causing plasma hyperosmolarity and dehydration", "endocrine"],
    ["metabolic acidosis", "decreased blood pH from acid accumulation or bicarbonate loss", "endocrine"],
    ["metabolic alkalosis", "increased blood pH from acid loss or alkali excess", "endocrine"],
    ["calcium homeostasis disruption", "disordered calcium regulation from parathyroid or vitamin D dysfunction", "endocrine"],
    ["pituitary dysfunction", "impaired anterior or posterior pituitary hormone secretion", "endocrine"],
    ["adrenal hyperfunction", "excessive secretion of adrenal hormones", "endocrine"],
    ["thyroid autoimmunity", "immune-mediated destruction or stimulation of thyroid gland", "endocrine"],
    ["hyperglycemia", "persistently elevated blood glucose levels causing microvascular damage", "endocrine"],
    ["hypoglycemia", "dangerously low blood glucose causing neuroglycopenic symptoms", "endocrine"],
    ["electrolyte imbalance", "disruption of sodium, potassium, or other electrolyte homeostasis", "endocrine"],
    ["gonadal dysfunction", "impaired sex hormone production affecting reproductive function", "endocrine"],
    ["growth hormone dysregulation", "abnormal growth hormone secretion affecting metabolism and growth", "endocrine"],

    // ── RENAL (15) ──
    ["glomerular filtration impairment", "reduced GFR from glomerular injury or perfusion decrease", "renal"],
    ["tubular necrosis", "death of renal tubular epithelial cells from ischemia or toxins", "renal"],
    ["nephrotic protein loss", "massive proteinuria from glomerular basement membrane damage", "renal"],
    ["renal interstitial inflammation", "inflammatory infiltration of renal interstitium", "renal"],
    ["urinary tract mucosal inflammation", "inflammation of urothelium from infection or irritation", "renal"],
    ["renal calculus obstruction", "mechanical obstruction by renal stones causing hydronephrosis", "renal"],
    ["glomerulonephritis", "immune-mediated inflammation of glomeruli", "renal"],
    ["renal tubular acidosis", "impaired renal acid excretion causing metabolic acidosis", "renal"],
    ["prerenal azotemia", "elevated BUN from decreased renal perfusion", "renal"],
    ["urinary retention", "inability to completely empty bladder", "renal"],
    ["renal papillary necrosis", "ischemic necrosis of renal papillae", "renal"],
    ["sodium retention", "impaired renal sodium excretion causing volume expansion", "renal"],
    ["potassium homeostasis disruption", "renal potassium excretion imbalance causing hyper- or hypokalemia", "renal"],
    ["renal cyst formation", "development of fluid-filled cysts in renal parenchyma", "renal"],
    ["obstructive uropathy", "impaired urine outflow causing upstream dilation and renal damage", "renal"],

    // ── IMMUNE/INFECTIOUS (20) ──
    ["systemic inflammatory response", "widespread inflammatory activation with cytokine release", "immune"],
    ["IgE-mediated hypersensitivity", "immediate allergic reaction mediated by IgE and mast cell degranulation", "immune"],
    ["immune complex deposition", "deposition of antigen-antibody complexes in tissues causing inflammation", "immune"],
    ["cell-mediated immune response", "T-cell mediated immune response against intracellular pathogens", "immune"],
    ["granulomatous inflammation", "formation of granulomas from chronic immune activation", "immune"],
    ["mast cell degranulation", "release of histamine and mediators from mast cells causing immediate hypersensitivity", "immune"],
    ["anaphylactic cascade", "systemic mast cell activation causing vasodilation, bronchospasm, and shock", "immune"],
    ["viral replication", "intracellular viral multiplication with host cell injury", "immune"],
    ["bacterial toxin release", "production of exotoxins or endotoxins by pathogenic bacteria", "immune"],
    ["sepsis cascade", "dysregulated host response to infection with organ dysfunction", "immune"],
    ["immune deficiency", "reduced ability to mount effective immune response against pathogens", "immune"],
    ["autoimmune tissue destruction", "immune system attacking self-tissues causing organ damage", "immune"],
    ["complement activation", "cascade activation of complement system causing inflammation and lysis", "immune"],
    ["cytokine storm", "excessive release of pro-inflammatory cytokines causing multi-organ damage", "immune"],
    ["parasitic tissue invasion", "parasitic organisms invading and damaging host tissues", "immune"],
    ["fungal colonization", "superficial or invasive growth of fungal organisms in host tissues", "immune"],
    ["lymphoid hyperplasia", "reactive enlargement of lymph nodes from antigenic stimulation", "immune"],
    ["immunosuppression", "pharmacological or pathological suppression of immune function", "immune"],
    ["type IV hypersensitivity", "delayed T-cell mediated immune reaction to allergens", "immune"],
    ["chronic low-grade inflammation", "persistent subclinical inflammatory state contributing to tissue damage", "immune"],

    // ── DERMATOLOGIC (15) ──
    ["epidermal barrier disruption", "impaired stratum corneum function causing transepidermal water loss", "dermatologic"],
    ["keratinocyte hyperproliferation", "accelerated turnover of keratinocytes causing scale formation", "dermatologic"],
    ["dermal inflammatory infiltrate", "immune cell infiltration into dermis causing erythema and edema", "dermatologic"],
    ["melanocyte dysplasia", "abnormal melanocyte growth and differentiation", "dermatologic"],
    ["sebaceous gland hyperactivity", "excessive sebum production causing comedone formation", "dermatologic"],
    ["urticarial vasodilation", "histamine-mediated dermal vasodilation and edema forming wheals", "dermatologic"],
    ["dermal fibrosis", "excessive collagen deposition in dermis causing scarring", "dermatologic"],
    ["parasitic skin infestation", "burrowing of parasitic organisms in epidermis", "dermatologic"],
    ["cutaneous vasculitis", "inflammation of dermal blood vessels causing purpura", "dermatologic"],
    ["follicular obstruction", "blockage of hair follicles causing inflammation and infection", "dermatologic"],
    ["photosensitivity reaction", "abnormal skin response to ultraviolet radiation", "dermatologic"],
    ["vesicle formation", "intraepidermal or subepidermal fluid collection forming blisters", "dermatologic"],
    ["wound healing impairment", "delayed or abnormal tissue repair process", "dermatologic"],
    ["pigmentation disorder", "abnormal melanin distribution or production in skin", "dermatologic"],
    ["subcutaneous fat inflammation", "inflammation of subcutaneous adipose tissue (panniculitis)", "dermatologic"],

    // ── MUSCULOSKELETAL (15) ──
    ["synovial inflammation", "inflammation of synovial membrane causing joint effusion and pain", "musculoskeletal"],
    ["cartilage degeneration", "progressive loss of articular cartilage from mechanical or enzymatic damage", "musculoskeletal"],
    ["crystal arthropathy", "deposition of monosodium urate or calcium crystals in joints", "musculoskeletal"],
    ["muscle inflammation", "inflammatory infiltration of skeletal muscle fibers (myositis)", "musculoskeletal"],
    ["tendon inflammation", "inflammation of tendons from overuse or systemic disease", "musculoskeletal"],
    ["bone mineral loss", "decreased bone mineral density from osteoclast-osteoblast imbalance", "musculoskeletal"],
    ["intervertebral disc degeneration", "progressive deterioration of intervertebral disc structure", "musculoskeletal"],
    ["ligament injury", "stretching or tearing of ligamentous structures", "musculoskeletal"],
    ["myofascial pain", "localized muscle pain from trigger points in muscle and fascia", "musculoskeletal"],
    ["enthesopathy", "inflammation at tendon or ligament insertion sites on bone", "musculoskeletal"],
    ["bone fracture physiology", "disruption of bone continuity with periosteal and soft tissue injury", "musculoskeletal"],
    ["joint instability", "loss of normal joint constraints allowing excessive motion", "musculoskeletal"],
    ["muscle spasm physiology", "involuntary sustained muscle contraction causing pain", "musculoskeletal"],
    ["osteoarticular infection", "bacterial invasion of bone or joint causing osteomyelitis or septic arthritis", "musculoskeletal"],
    ["spinal stenosis", "narrowing of spinal canal compressing neural elements", "musculoskeletal"],

    // ── HEMATOLOGIC (15) ──
    ["iron depletion", "exhaustion of iron stores reducing hemoglobin synthesis", "hematologic"],
    ["megaloblastic erythropoiesis", "impaired DNA synthesis in red cell precursors from B12 or folate deficiency", "hematologic"],
    ["hemoglobin polymerization", "sickling of red blood cells from HbS polymerization under deoxygenation", "hematologic"],
    ["coagulation cascade activation", "pathological activation of clotting factors causing thrombosis", "hematologic"],
    ["platelet consumption", "excessive platelet utilization causing thrombocytopenia", "hematologic"],
    ["disseminated intravascular coagulation", "systemic activation of coagulation and fibrinolysis", "hematologic"],
    ["hemolysis", "accelerated destruction of red blood cells releasing hemoglobin", "hematologic"],
    ["bone marrow suppression", "impaired hematopoiesis from toxins, drugs, or infiltration", "hematologic"],
    ["impaired erythropoiesis", "reduced red blood cell production from chronic disease or nutrient deficiency", "hematologic"],
    ["hypercoagulable state", "increased tendency for pathological clot formation", "hematologic"],
    ["white cell dysregulation", "abnormal leukocyte count or function", "hematologic"],
    ["fibrinolysis impairment", "reduced ability to dissolve blood clots", "hematologic"],
    ["chronic blood loss", "ongoing slow hemorrhage causing iron depletion", "hematologic"],
    ["lymphoproliferative process", "abnormal expansion of lymphoid cell populations", "hematologic"],
    ["erythrocyte fragmentation", "mechanical shearing of red blood cells in microvasculature", "hematologic"],

    // ── REPRODUCTIVE (5) ──
    ["ectopic implantation", "implantation of embryo outside uterine cavity", "reproductive"],
    ["placental dysfunction", "impaired placental perfusion or function causing fetal compromise", "reproductive"],
    ["uterine smooth muscle dysfunction", "abnormal uterine contractility or growth", "reproductive"],
    ["ovarian follicular dysfunction", "disordered ovarian follicle development and ovulation", "reproductive"],
    ["endometrial hyperplasia", "excessive proliferation of uterine endometrium", "reproductive"],
  ];
}

// ── SYMPTOM → PHYSIOLOGY MAPPINGS ──
// [symptom_name, physiology_state_name, confidence_score]
type SymPhysio = [string, string, number];

function generateSymptomPhysiologyMap(): SymPhysio[] {
  return [
    // RESPIRATORY SYMPTOMS
    ["cough", "airway inflammation", 0.85],
    ["cough", "bronchoconstriction", 0.75],
    ["cough", "mucus hypersecretion", 0.80],
    ["cough", "pulmonary vascular congestion", 0.55],
    ["cough", "pharyngeal inflammation", 0.60],
    ["cough", "gastroesophageal reflux", 0.50],
    ["cough", "airway obstruction", 0.65],
    ["cough", "pulmonary fibrosis", 0.55],
    ["chronic cough", "bronchiolar destruction", 0.75],
    ["chronic cough", "airway inflammation", 0.80],
    ["chronic cough", "mucus hypersecretion", 0.80],
    ["chronic cough", "gastroesophageal reflux", 0.60],
    ["chronic productive cough", "bronchiolar destruction", 0.85],
    ["chronic productive cough", "mucus hypersecretion", 0.90],
    ["productive cough", "mucus hypersecretion", 0.90],
    ["productive cough", "airway inflammation", 0.80],
    ["productive cough", "pulmonary parenchymal necrosis", 0.60],
    ["barking cough", "laryngeal inflammation", 0.90],
    ["barking cough", "upper airway edema", 0.85],
    ["paroxysmal cough", "airway inflammation", 0.80],
    ["paroxysmal cough", "bronchial hyperreactivity", 0.75],
    ["dry cough", "airway inflammation", 0.70],
    ["dry cough", "pulmonary fibrosis", 0.65],
    ["dry cough", "laryngeal inflammation", 0.60],
    ["nocturnal cough", "bronchoconstriction", 0.75],
    ["nocturnal cough", "gastroesophageal reflux", 0.65],
    ["shortness of breath", "bronchoconstriction", 0.80],
    ["shortness of breath", "pulmonary vascular congestion", 0.75],
    ["shortness of breath", "alveolar damage", 0.70],
    ["shortness of breath", "ventilation-perfusion mismatch", 0.75],
    ["shortness of breath", "left ventricular systolic dysfunction", 0.65],
    ["shortness of breath", "pulmonary edema", 0.75],
    ["shortness of breath", "hypoxemic respiratory failure", 0.80],
    ["shortness of breath", "anaphylactic cascade", 0.70],
    ["shortness of breath", "respiratory muscle fatigue", 0.60],
    ["dyspnea", "bronchoconstriction", 0.80],
    ["dyspnea", "pulmonary vascular congestion", 0.75],
    ["dyspnea", "ventilation-perfusion mismatch", 0.75],
    ["dyspnea", "pulmonary edema", 0.75],
    ["dyspnea", "alveolar damage", 0.70],
    ["dyspnea on exertion", "left ventricular systolic dysfunction", 0.80],
    ["dyspnea on exertion", "cardiac output reduction", 0.75],
    ["dyspnea on exertion", "pulmonary hypertension", 0.65],
    ["dyspnea on exertion", "iron depletion", 0.50],
    ["exertional dyspnea", "cardiac valve dysfunction", 0.75],
    ["exertional dyspnea", "left ventricular systolic dysfunction", 0.80],
    ["worsening dyspnea", "bronchiolar destruction", 0.80],
    ["worsening dyspnea", "airway obstruction", 0.85],
    ["progressive dyspnea", "pulmonary fibrosis", 0.85],
    ["progressive dyspnea", "pulmonary hypertension", 0.70],
    ["severe dyspnea", "alveolar damage", 0.85],
    ["severe dyspnea", "hypoxemic respiratory failure", 0.90],
    ["sudden dyspnea", "ventilation-perfusion mismatch", 0.85],
    ["sudden dyspnea", "pneumothorax physiology", 0.80],
    ["wheezing", "bronchoconstriction", 0.90],
    ["wheezing", "airway inflammation", 0.80],
    ["wheezing", "airway obstruction", 0.80],
    ["wheezing", "bronchial hyperreactivity", 0.85],
    ["wheezing", "mucus hypersecretion", 0.60],
    ["stridor", "upper airway edema", 0.90],
    ["stridor", "laryngeal inflammation", 0.85],
    ["stridor", "airway obstruction", 0.85],
    ["sputum production", "mucus hypersecretion", 0.90],
    ["sputum production", "airway inflammation", 0.75],
    ["increased sputum", "mucus hypersecretion", 0.90],
    ["purulent sputum", "airway inflammation", 0.85],
    ["purulent sputum", "mucus hypersecretion", 0.80],
    ["foul-smelling sputum", "pulmonary parenchymal necrosis", 0.85],
    ["hemoptysis", "pulmonary parenchymal necrosis", 0.75],
    ["hemoptysis", "pulmonary vascular congestion", 0.60],
    ["hemoptysis", "gastrointestinal hemorrhage", 0.30],
    ["recurrent hemoptysis", "bronchiolar destruction", 0.70],
    ["sneezing", "nasal mucosal inflammation", 0.90],
    ["sneezing", "IgE-mediated hypersensitivity", 0.80],
    ["runny nose", "nasal mucosal inflammation", 0.90],
    ["runny nose", "viral replication", 0.70],
    ["nasal congestion", "nasal mucosal inflammation", 0.90],
    ["nasal congestion", "sinusoidal mucosal inflammation", 0.75],
    ["purulent nasal discharge", "sinusoidal mucosal inflammation", 0.85],
    ["postnasal drip", "nasal mucosal inflammation", 0.80],
    ["postnasal drip", "sinusoidal mucosal inflammation", 0.75],
    ["tachypnea", "ventilation-perfusion mismatch", 0.70],
    ["tachypnea", "metabolic acidosis", 0.70],
    ["tachypnea", "hypoxemic respiratory failure", 0.80],
    ["tachypnea", "sepsis cascade", 0.65],
    ["hoarseness", "laryngeal inflammation", 0.85],
    ["hoarseness", "upper airway edema", 0.55],
    ["chest tightness", "bronchoconstriction", 0.85],
    ["chest tightness", "bronchial hyperreactivity", 0.80],
    ["pleuritic chest pain", "pleural inflammation", 0.90],
    ["pleuritic chest pain", "pulmonary parenchymal necrosis", 0.50],
    ["pleuritic chest pain", "pneumothorax physiology", 0.70],
    ["hypoxemia", "ventilation-perfusion mismatch", 0.90],
    ["hypoxemia", "alveolar damage", 0.85],
    ["hypoxemia", "hypoxemic respiratory failure", 0.95],
    ["cyanosis", "hypoxemic respiratory failure", 0.85],
    ["cyanosis", "ventilation-perfusion mismatch", 0.80],
    ["use of accessory muscles", "respiratory muscle fatigue", 0.85],
    ["use of accessory muscles", "airway obstruction", 0.80],
    ["crackles on auscultation", "pulmonary edema", 0.80],
    ["crackles on auscultation", "pulmonary vascular congestion", 0.75],
    ["crackles", "pulmonary edema", 0.80],
    ["velcro crackles", "pulmonary fibrosis", 0.90],
    ["bilateral crackles", "pulmonary edema", 0.85],
    ["decreased breath sounds", "pneumothorax physiology", 0.85],
    ["decreased breath sounds", "atelectasis", 0.75],
    ["dullness to percussion", "pleural inflammation", 0.80],
    ["reduced smell", "nasal mucosal inflammation", 0.75],
    ["reduced smell", "sinusoidal mucosal inflammation", 0.70],
    ["clubbing", "pulmonary fibrosis", 0.75],
    ["clubbing", "chronic blood loss", 0.30],

    // CARDIOVASCULAR SYMPTOMS
    ["chest pain", "myocardial ischemia", 0.80],
    ["chest pain", "pericardial inflammation", 0.65],
    ["chest pain", "pleural inflammation", 0.55],
    ["chest pain", "gastroesophageal reflux", 0.45],
    ["chest pain", "aortic wall degeneration", 0.50],
    ["chest pain", "myocardial necrosis", 0.75],
    ["chest pressure", "myocardial ischemia", 0.85],
    ["chest pressure", "myocardial necrosis", 0.80],
    ["chest pain at rest", "myocardial ischemia", 0.85],
    ["chest pain at rest", "coronary vasospasm", 0.75],
    ["sharp chest pain", "pericardial inflammation", 0.85],
    ["sharp chest pain", "pleural inflammation", 0.70],
    ["chest pain worse with inspiration", "pericardial inflammation", 0.80],
    ["chest pain worse with inspiration", "pleural inflammation", 0.85],
    ["chest pain relieved by leaning forward", "pericardial inflammation", 0.90],
    ["tearing chest pain", "aortic wall degeneration", 0.90],
    ["sudden chest pain", "pneumothorax physiology", 0.80],
    ["sudden chest pain", "myocardial ischemia", 0.65],
    ["sudden severe pain", "aortic wall degeneration", 0.85],
    ["left arm pain", "myocardial ischemia", 0.75],
    ["jaw pain", "myocardial ischemia", 0.55],
    ["pain radiating to arm", "myocardial ischemia", 0.75],
    ["palpitations", "cardiac arrhythmia", 0.85],
    ["palpitations", "thyroid hormone excess", 0.55],
    ["palpitations", "iron depletion", 0.40],
    ["palpitations", "anaphylactic cascade", 0.35],
    ["rapid heartbeat", "cardiac arrhythmia", 0.90],
    ["irregular heartbeat", "cardiac arrhythmia", 0.95],
    ["tachycardia", "cardiac arrhythmia", 0.70],
    ["tachycardia", "systemic inflammatory response", 0.65],
    ["tachycardia", "fluid overload", 0.45],
    ["tachycardia", "anaphylactic cascade", 0.60],
    ["tachycardia", "sepsis cascade", 0.65],
    ["tachycardia", "thyroid hormone excess", 0.60],
    ["diaphoresis", "myocardial ischemia", 0.70],
    ["diaphoresis", "systemic inflammatory response", 0.50],
    ["diaphoresis", "hypoglycemia", 0.65],
    ["peripheral edema", "fluid overload", 0.80],
    ["peripheral edema", "right heart failure", 0.75],
    ["peripheral edema", "venous valve incompetence", 0.65],
    ["peripheral edema", "sodium retention", 0.70],
    ["ankle edema", "right heart failure", 0.70],
    ["ankle edema", "fluid overload", 0.70],
    ["leg swelling", "venous thrombosis", 0.80],
    ["leg swelling", "fluid overload", 0.60],
    ["leg swelling", "venous valve incompetence", 0.65],
    ["orthopnea", "pulmonary vascular congestion", 0.85],
    ["orthopnea", "left ventricular systolic dysfunction", 0.80],
    ["paroxysmal nocturnal dyspnea", "left ventricular systolic dysfunction", 0.85],
    ["paroxysmal nocturnal dyspnea", "pulmonary vascular congestion", 0.85],
    ["jugular venous distension", "right heart failure", 0.85],
    ["jugular venous distension", "cardiac tamponade physiology", 0.80],
    ["jugular venous distension", "fluid overload", 0.70],
    ["muffled heart sounds", "cardiac tamponade physiology", 0.90],
    ["pulsus paradoxus", "cardiac tamponade physiology", 0.85],
    ["syncope", "cardiac output reduction", 0.75],
    ["syncope", "cardiac arrhythmia", 0.70],
    ["syncope", "cerebral ischemia", 0.65],
    ["syncope", "systemic hypoperfusion", 0.70],
    ["hypotension", "systemic hypoperfusion", 0.85],
    ["hypotension", "vasodilatory shock", 0.80],
    ["hypotension", "cardiac output reduction", 0.75],
    ["hypotension", "anaphylactic cascade", 0.75],
    ["systolic murmur", "cardiac valve dysfunction", 0.85],
    ["new heart murmur", "cardiac valve dysfunction", 0.80],
    ["new heart murmur", "myocardial inflammation", 0.45],
    ["mid-systolic click", "cardiac valve dysfunction", 0.80],
    ["calf pain", "venous thrombosis", 0.80],
    ["calf tenderness", "venous thrombosis", 0.80],
    ["leg warmth", "venous thrombosis", 0.65],
    ["leg redness", "venous thrombosis", 0.60],
    ["intermittent claudication", "peripheral vascular insufficiency", 0.90],
    ["leg pain with walking", "peripheral vascular insufficiency", 0.85],
    ["rest pain", "peripheral vascular insufficiency", 0.80],
    ["weak pulses", "peripheral vascular insufficiency", 0.80],
    ["cool extremities", "peripheral vascular insufficiency", 0.70],
    ["blood pressure differential", "aortic wall degeneration", 0.80],
    ["pulse deficit", "aortic wall degeneration", 0.75],
    ["pericardial friction rub", "pericardial inflammation", 0.90],
    ["weight gain", "fluid overload", 0.60],
    ["weight gain", "thyroid hormone deficiency", 0.60],
    ["weight gain", "insulin resistance", 0.50],
    ["visible enlarged veins", "venous valve incompetence", 0.90],
    ["angina", "myocardial ischemia", 0.90],

    // NEUROLOGICAL SYMPTOMS
    ["headache", "neuroinflammation", 0.50],
    ["headache", "intracranial pressure elevation", 0.55],
    ["headache", "meningeal irritation", 0.50],
    ["headache", "cortical spreading depression", 0.50],
    ["headache", "sinusoidal mucosal inflammation", 0.40],
    ["severe headache", "meningeal irritation", 0.75],
    ["severe headache", "intracranial pressure elevation", 0.70],
    ["severe headache", "cerebral hemorrhage", 0.65],
    ["severe headache", "increased systemic vascular resistance", 0.55],
    ["unilateral headache", "cortical spreading depression", 0.85],
    ["unilateral headache", "trigeminal nerve irritation", 0.70],
    ["throbbing headache", "cortical spreading depression", 0.80],
    ["bilateral headache", "myofascial pain", 0.70],
    ["bilateral headache", "central sensitization", 0.55],
    ["pressing quality headache", "myofascial pain", 0.75],
    ["thunderclap headache", "cerebral hemorrhage", 0.90],
    ["thunderclap headache", "cerebral vasospasm", 0.75],
    ["worst headache of life", "cerebral hemorrhage", 0.90],
    ["morning headache", "intracranial pressure elevation", 0.60],
    ["morning headache", "pulmonary hypertension", 0.30],
    ["neck stiffness", "meningeal irritation", 0.85],
    ["neck stiffness", "myofascial pain", 0.45],
    ["photophobia", "meningeal irritation", 0.75],
    ["photophobia", "cortical spreading depression", 0.70],
    ["phonophobia", "cortical spreading depression", 0.75],
    ["visual aura", "cortical spreading depression", 0.90],
    ["seizures", "seizure activity", 0.95],
    ["seizures", "neuroinflammation", 0.45],
    ["seizure", "seizure activity", 0.95],
    ["convulsions", "seizure activity", 0.90],
    ["loss of consciousness", "seizure activity", 0.65],
    ["loss of consciousness", "cerebral ischemia", 0.60],
    ["confusion", "cerebral ischemia", 0.55],
    ["confusion", "hepatic encephalopathy", 0.60],
    ["confusion", "intracranial pressure elevation", 0.55],
    ["confusion", "sepsis cascade", 0.50],
    ["altered mental status", "cerebral ischemia", 0.65],
    ["altered mental status", "sepsis cascade", 0.65],
    ["altered mental status", "intracranial pressure elevation", 0.60],
    ["altered mental status", "hepatic encephalopathy", 0.55],
    ["altered mental status", "hypoglycemia", 0.60],
    ["sudden weakness one side", "cerebral ischemia", 0.90],
    ["facial droop", "cerebral ischemia", 0.85],
    ["facial droop", "facial nerve paralysis", 0.85],
    ["speech difficulty", "cerebral ischemia", 0.80],
    ["arm weakness", "cerebral ischemia", 0.80],
    ["sudden confusion", "cerebral ischemia", 0.75],
    ["visual loss", "cerebral ischemia", 0.65],
    ["blurred vision", "intracranial pressure elevation", 0.50],
    ["blurred vision", "hyperglycemia", 0.55],
    ["blurred vision", "increased systemic vascular resistance", 0.45],
    ["dizziness", "vestibular dysfunction", 0.65],
    ["dizziness", "cardiac output reduction", 0.50],
    ["dizziness", "cerebral ischemia", 0.45],
    ["dizziness", "iron depletion", 0.40],
    ["dizziness", "autonomic dysregulation", 0.50],
    ["resting tremor", "dopaminergic depletion", 0.90],
    ["bradykinesia", "dopaminergic depletion", 0.90],
    ["rigidity", "dopaminergic depletion", 0.85],
    ["postural instability", "dopaminergic depletion", 0.75],
    ["shuffling gait", "dopaminergic depletion", 0.80],
    ["numbness tingling", "peripheral neuropathy", 0.80],
    ["numbness tingling", "demyelination", 0.65],
    ["tingling in extremities", "ascending paralysis", 0.70],
    ["tingling in extremities", "peripheral neuropathy", 0.75],
    ["hand numbness", "peripheral nerve compression", 0.85],
    ["tingling in fingers", "peripheral nerve compression", 0.85],
    ["paresthesias", "peripheral neuropathy", 0.80],
    ["paresthesias", "demyelination", 0.65],
    ["leg numbness", "nerve root compression", 0.80],
    ["leg weakness", "nerve root compression", 0.70],
    ["ascending weakness", "ascending paralysis", 0.90],
    ["areflexia", "ascending paralysis", 0.85],
    ["difficulty walking", "dopaminergic depletion", 0.60],
    ["difficulty walking", "ascending paralysis", 0.60],
    ["difficulty walking", "spinal cord compression", 0.55],
    ["unilateral facial weakness", "facial nerve paralysis", 0.95],
    ["facial drooping", "facial nerve paralysis", 0.90],
    ["inability to close eye", "facial nerve paralysis", 0.85],
    ["positional vertigo", "vestibular dysfunction", 0.90],
    ["brief episodes of dizziness", "vestibular dysfunction", 0.85],
    ["episodic vertigo", "vestibular dysfunction", 0.90],
    ["nystagmus", "vestibular dysfunction", 0.80],
    ["progressive memory loss", "neurodegenerative protein aggregation", 0.85],
    ["progressive memory loss", "cholinergic deficit", 0.80],
    ["disorientation", "neurodegenerative protein aggregation", 0.70],
    ["language difficulties", "neurodegenerative protein aggregation", 0.65],
    ["sciatica", "nerve root compression", 0.90],
    ["positive straight leg raise", "nerve root compression", 0.85],
    ["foot drop", "nerve root compression", 0.80],
    ["severe facial pain", "trigeminal nerve irritation", 0.90],
    ["electric shock-like pain", "trigeminal nerve irritation", 0.90],
    ["unilateral face pain", "trigeminal nerve irritation", 0.85],
    ["Kernig sign", "meningeal irritation", 0.85],
    ["Brudzinski sign", "meningeal irritation", 0.85],
    ["Tinel sign positive", "peripheral nerve compression", 0.80],
    ["Phalen test positive", "peripheral nerve compression", 0.80],
    ["optic neuritis", "demyelination", 0.85],
    ["Lhermitte sign", "demyelination", 0.80],

    // GASTROINTESTINAL SYMPTOMS
    ["nausea", "gastric mucosal erosion", 0.55],
    ["nausea", "intestinal inflammation", 0.50],
    ["nausea", "intracranial pressure elevation", 0.40],
    ["nausea", "hepatocellular injury", 0.45],
    ["nausea", "pancreatic acinar cell injury", 0.55],
    ["nausea", "vestibular dysfunction", 0.50],
    ["nausea", "diabetic ketoacidosis physiology", 0.50],
    ["vomiting", "intracranial pressure elevation", 0.50],
    ["vomiting", "intestinal obstruction", 0.75],
    ["vomiting", "gastric mucosal erosion", 0.55],
    ["vomiting", "pancreatic acinar cell injury", 0.55],
    ["vomiting", "vestibular dysfunction", 0.50],
    ["diarrhea", "intestinal inflammation", 0.80],
    ["diarrhea", "intestinal motility dysfunction", 0.65],
    ["diarrhea", "malabsorption", 0.55],
    ["diarrhea", "bacterial toxin release", 0.65],
    ["diarrhea", "intestinal barrier disruption", 0.60],
    ["diarrhea", "thyroid hormone excess", 0.35],
    ["chronic diarrhea", "intestinal inflammation", 0.80],
    ["chronic diarrhea", "malabsorption", 0.75],
    ["chronic diarrhea", "visceral hypersensitivity", 0.55],
    ["bloody diarrhea", "colonic mucosal ulceration", 0.90],
    ["bloody diarrhea", "intestinal inflammation", 0.85],
    ["abdominal pain", "peritoneal irritation", 0.60],
    ["abdominal pain", "intestinal inflammation", 0.55],
    ["abdominal pain", "intestinal motility dysfunction", 0.50],
    ["abdominal pain", "gastric mucosal erosion", 0.50],
    ["abdominal pain", "visceral hypersensitivity", 0.50],
    ["abdominal cramps", "intestinal motility dysfunction", 0.75],
    ["abdominal cramps", "intestinal inflammation", 0.65],
    ["severe epigastric pain", "pancreatic acinar cell injury", 0.85],
    ["severe epigastric pain", "gastric mucosal erosion", 0.70],
    ["epigastric pain", "gastric mucosal erosion", 0.80],
    ["epigastric pain", "gastroesophageal reflux", 0.60],
    ["epigastric pain", "helicobacter pylori infection", 0.65],
    ["burning stomach pain", "gastric mucosal erosion", 0.85],
    ["burning stomach pain", "helicobacter pylori infection", 0.70],
    ["right upper quadrant pain", "gallbladder inflammation", 0.80],
    ["right upper quadrant pain", "biliary obstruction", 0.75],
    ["right upper quadrant pain", "hepatocellular injury", 0.60],
    ["right lower quadrant pain", "appendiceal obstruction", 0.85],
    ["right lower quadrant pain", "peritoneal irritation", 0.70],
    ["left lower quadrant pain", "diverticular inflammation", 0.85],
    ["periumbilical pain migrating to RLQ", "appendiceal obstruction", 0.90],
    ["pain radiating to back", "pancreatic acinar cell injury", 0.80],
    ["colicky abdominal pain", "intestinal obstruction", 0.85],
    ["colicky abdominal pain", "renal calculus obstruction", 0.65],
    ["abdominal distension", "intestinal obstruction", 0.80],
    ["abdominal distension", "portal hypertension", 0.55],
    ["abdominal tenderness", "peritoneal irritation", 0.80],
    ["rebound tenderness", "peritoneal irritation", 0.90],
    ["guarding", "peritoneal irritation", 0.85],
    ["Murphy sign positive", "gallbladder inflammation", 0.85],
    ["heartburn", "gastroesophageal reflux", 0.90],
    ["acid regurgitation", "gastroesophageal reflux", 0.90],
    ["dysphagia", "esophageal dysmotility", 0.70],
    ["dysphagia", "upper airway edema", 0.45],
    ["difficulty swallowing", "pharyngeal inflammation", 0.65],
    ["difficulty swallowing", "upper airway edema", 0.55],
    ["bloating", "intestinal motility dysfunction", 0.70],
    ["bloating", "visceral hypersensitivity", 0.65],
    ["bloating", "bacterial overgrowth", 0.60],
    ["constipation", "colonic dysmotility", 0.80],
    ["constipation", "intestinal motility dysfunction", 0.70],
    ["constipation", "thyroid hormone deficiency", 0.40],
    ["jaundice", "biliary obstruction", 0.80],
    ["jaundice", "hepatocellular injury", 0.80],
    ["jaundice", "hemolysis", 0.55],
    ["dark urine", "biliary obstruction", 0.75],
    ["dark urine", "hepatocellular injury", 0.70],
    ["clay-colored stools", "biliary obstruction", 0.85],
    ["melena", "gastrointestinal hemorrhage", 0.90],
    ["melena", "gastric mucosal erosion", 0.70],
    ["hematemesis", "gastrointestinal hemorrhage", 0.90],
    ["hematemesis", "gastric mucosal erosion", 0.80],
    ["rectal bleeding", "colonic mucosal ulceration", 0.75],
    ["rectal bleeding", "gastrointestinal hemorrhage", 0.70],
    ["bloody stool", "colonic mucosal ulceration", 0.80],
    ["ascites", "portal hypertension", 0.85],
    ["ascites", "nephrotic protein loss", 0.55],
    ["loss of appetite", "hepatocellular injury", 0.55],
    ["loss of appetite", "systemic inflammatory response", 0.50],
    ["early satiety", "gastric mucosal erosion", 0.55],
    ["steatorrhea", "malabsorption", 0.90],
    ["tenesmus", "colonic mucosal ulceration", 0.80],
    ["urgency", "colonic mucosal ulceration", 0.70],
    ["fecal occult blood", "gastrointestinal hemorrhage", 0.80],
    ["spider angiomas", "portal hypertension", 0.75],
    ["palmar erythema", "hepatic fibrosis", 0.70],
    ["hepatomegaly", "hepatocellular injury", 0.70],
    ["splenomegaly", "portal hypertension", 0.65],
    ["splenomegaly", "lymphoid hyperplasia", 0.55],
    ["inability to pass gas", "intestinal obstruction", 0.80],
    ["high-pitched bowel sounds", "intestinal obstruction", 0.75],
    ["pain after fatty meals", "gallbladder inflammation", 0.75],
    ["pain after fatty meals", "biliary obstruction", 0.65],
    ["referred shoulder pain", "gallbladder inflammation", 0.55],
    ["perianal disease", "intestinal inflammation", 0.70],
    ["mouth ulcers", "intestinal inflammation", 0.50],
    ["mucus in stool", "visceral hypersensitivity", 0.55],
    ["mucus in stool", "intestinal inflammation", 0.50],
    ["symptom relief after defecation", "visceral hypersensitivity", 0.70],
    ["uvular deviation", "pharyngeal inflammation", 0.65],

    // ENDOCRINE SYMPTOMS
    ["polyuria", "hyperglycemia", 0.80],
    ["polyuria", "insulin deficiency", 0.75],
    ["polydipsia", "hyperglycemia", 0.80],
    ["polydipsia", "insulin deficiency", 0.75],
    ["polyphagia", "insulin deficiency", 0.70],
    ["Kussmaul breathing", "diabetic ketoacidosis physiology", 0.90],
    ["Kussmaul breathing", "metabolic acidosis", 0.85],
    ["fruity breath odor", "diabetic ketoacidosis physiology", 0.90],
    ["fatigue", "thyroid hormone deficiency", 0.50],
    ["fatigue", "iron depletion", 0.55],
    ["fatigue", "insulin resistance", 0.40],
    ["fatigue", "cortisol deficiency", 0.50],
    ["fatigue", "impaired erythropoiesis", 0.50],
    ["fatigue", "systemic inflammatory response", 0.45],
    ["fatigue", "left ventricular systolic dysfunction", 0.40],
    ["cold intolerance", "thyroid hormone deficiency", 0.80],
    ["heat intolerance", "thyroid hormone excess", 0.80],
    ["weight loss", "thyroid hormone excess", 0.55],
    ["weight loss", "insulin deficiency", 0.50],
    ["weight loss", "malabsorption", 0.55],
    ["weight loss", "systemic inflammatory response", 0.45],
    ["tremor", "thyroid hormone excess", 0.70],
    ["tremor", "dopaminergic depletion", 0.60],
    ["sweating", "thyroid hormone excess", 0.65],
    ["sweating", "hypoglycemia", 0.60],
    ["moon face", "cortisol excess", 0.85],
    ["central obesity", "cortisol excess", 0.75],
    ["central obesity", "insulin resistance", 0.65],
    ["purple striae", "cortisol excess", 0.85],
    ["buffalo hump", "cortisol excess", 0.80],
    ["hyperpigmentation", "cortisol deficiency", 0.80],
    ["salt craving", "cortisol deficiency", 0.70],
    ["dry skin", "thyroid hormone deficiency", 0.65],
    ["hair loss", "thyroid hormone deficiency", 0.55],
    ["hair loss", "hyperandrogenism", 0.50],
    ["irregular periods", "hyperandrogenism", 0.70],
    ["irregular periods", "ovarian follicular dysfunction", 0.75],
    ["hirsutism", "hyperandrogenism", 0.80],
    ["acne", "hyperandrogenism", 0.55],
    ["acne", "sebaceous gland hyperactivity", 0.70],
    ["exophthalmos", "thyroid autoimmunity", 0.80],
    ["neck lump", "thyroid autoimmunity", 0.45],
    ["bradycardia", "thyroid hormone deficiency", 0.65],
    ["menstrual irregularities", "thyroid hormone deficiency", 0.50],
    ["menstrual irregularities", "thyroid hormone excess", 0.45],
    ["menstrual irregularities", "gonadal dysfunction", 0.60],
    ["numbness in feet", "peripheral neuropathy", 0.80],
    ["numbness in feet", "hyperglycemia", 0.55],
    ["slow wound healing", "hyperglycemia", 0.70],
    ["frequent infections", "hyperglycemia", 0.50],
    ["frequent infections", "immune deficiency", 0.65],
    ["BMI >30", "insulin resistance", 0.60],
    ["dehydration", "diabetic ketoacidosis physiology", 0.65],
    ["dehydration", "hyperglycemia", 0.55],

    // RENAL SYMPTOMS
    ["dysuria", "urinary tract mucosal inflammation", 0.90],
    ["urinary frequency", "urinary tract mucosal inflammation", 0.80],
    ["urinary urgency", "urinary tract mucosal inflammation", 0.75],
    ["suprapubic pain", "urinary tract mucosal inflammation", 0.75],
    ["hematuria", "glomerulonephritis", 0.70],
    ["hematuria", "urinary tract mucosal inflammation", 0.60],
    ["hematuria", "renal calculus obstruction", 0.70],
    ["cloudy urine", "urinary tract mucosal inflammation", 0.65],
    ["foul-smelling urine", "urinary tract mucosal inflammation", 0.60],
    ["flank pain", "renal calculus obstruction", 0.80],
    ["flank pain", "renal interstitial inflammation", 0.70],
    ["severe flank pain", "renal calculus obstruction", 0.90],
    ["colicky pain", "renal calculus obstruction", 0.85],
    ["pain radiating to groin", "renal calculus obstruction", 0.80],
    ["costovertebral angle tenderness", "renal interstitial inflammation", 0.85],
    ["decreased urine output", "glomerular filtration impairment", 0.80],
    ["decreased urine output", "prerenal azotemia", 0.70],
    ["oliguria", "glomerular filtration impairment", 0.75],
    ["oliguria", "tubular necrosis", 0.70],
    ["edema", "sodium retention", 0.70],
    ["edema", "nephrotic protein loss", 0.65],
    ["edema", "fluid overload", 0.70],
    ["severe edema", "nephrotic protein loss", 0.85],
    ["periorbital edema", "nephrotic protein loss", 0.80],
    ["foamy urine", "nephrotic protein loss", 0.85],
    ["proteinuria", "glomerulonephritis", 0.80],
    ["proteinuria", "nephrotic protein loss", 0.85],
    ["dark urine", "hemolysis", 0.50],
    ["pruritus", "renal interstitial inflammation", 0.35],
    ["nocturia", "glomerular filtration impairment", 0.45],
    ["muscle cramps", "electrolyte imbalance", 0.65],

    // IMMUNE/INFECTIOUS SYMPTOMS
    ["fever", "systemic inflammatory response", 0.70],
    ["fever", "viral replication", 0.65],
    ["fever", "bacterial toxin release", 0.65],
    ["fever", "cell-mediated immune response", 0.55],
    ["high fever", "systemic inflammatory response", 0.80],
    ["high fever", "sepsis cascade", 0.65],
    ["sustained fever", "systemic inflammatory response", 0.80],
    ["sustained fever", "bacterial toxin release", 0.70],
    ["cyclical fever", "parasitic tissue invasion", 0.85],
    ["low-grade fever", "chronic low-grade inflammation", 0.65],
    ["low-grade fever", "viral replication", 0.60],
    ["chills", "systemic inflammatory response", 0.75],
    ["chills", "bacterial toxin release", 0.70],
    ["night sweats", "systemic inflammatory response", 0.65],
    ["night sweats", "cell-mediated immune response", 0.60],
    ["lymphadenopathy", "lymphoid hyperplasia", 0.80],
    ["lymphadenopathy", "cell-mediated immune response", 0.65],
    ["cervical lymphadenopathy", "lymphoid hyperplasia", 0.75],
    ["anterior cervical lymphadenopathy", "lymphoid hyperplasia", 0.75],
    ["malaise", "systemic inflammatory response", 0.65],
    ["malaise", "viral replication", 0.60],
    ["body aches", "systemic inflammatory response", 0.70],
    ["body aches", "viral replication", 0.65],
    ["myalgia", "systemic inflammatory response", 0.70],
    ["myalgia", "viral replication", 0.65],
    ["rash", "dermal inflammatory infiltrate", 0.55],
    ["rash", "viral replication", 0.45],
    ["maculopapular rash", "viral replication", 0.70],
    ["maculopapular rash", "dermal inflammatory infiltrate", 0.65],
    ["vesicular rash", "viral replication", 0.80],
    ["pruritic rash", "IgE-mediated hypersensitivity", 0.55],
    ["pruritic rash", "dermal inflammatory infiltrate", 0.60],
    ["petechiae", "platelet consumption", 0.70],
    ["petechiae", "cutaneous vasculitis", 0.60],
    ["petechial rash", "platelet consumption", 0.75],
    ["petechial rash", "disseminated intravascular coagulation", 0.55],
    ["sore throat", "pharyngeal inflammation", 0.85],
    ["sore throat", "viral replication", 0.60],
    ["severe sore throat", "pharyngeal inflammation", 0.90],
    ["tonsillar exudates", "pharyngeal inflammation", 0.80],
    ["tonsillar exudates", "bacterial toxin release", 0.65],
    ["enlarged tonsils", "lymphoid hyperplasia", 0.75],
    ["oral thrush", "fungal colonization", 0.85],
    ["oral thrush", "immune deficiency", 0.65],
    ["skin redness", "dermal inflammatory infiltrate", 0.80],
    ["warmth over area", "dermal inflammatory infiltrate", 0.80],
    ["swelling", "dermal inflammatory infiltrate", 0.65],
    ["pain at site", "dermal inflammatory infiltrate", 0.60],
    ["recurrent infections", "immune deficiency", 0.80],
    ["loss of taste", "viral replication", 0.70],
    ["loss of smell", "viral replication", 0.70],
    ["joint pain", "synovial inflammation", 0.65],
    ["joint pain", "crystal arthropathy", 0.50],
    ["joint pain", "viral replication", 0.35],
    ["retro-orbital pain", "systemic inflammatory response", 0.60],
    ["conjunctival suffusion", "systemic inflammatory response", 0.55],
    ["drooling", "upper airway edema", 0.60],
    ["drooling", "pharyngeal inflammation", 0.55],
    ["trismus", "pharyngeal inflammation", 0.65],
    ["muffled voice", "upper airway edema", 0.70],
    ["Koplik spots", "viral replication", 0.90],
    ["rash in different stages", "viral replication", 0.85],
    ["parotid gland swelling", "viral replication", 0.85],
    ["whooping sound", "airway inflammation", 0.80],
    ["post-tussive vomiting", "airway inflammation", 0.70],
    ["conjunctivitis", "viral replication", 0.50],
    ["unilateral vesicular rash", "viral replication", 0.85],
    ["dermatomal distribution", "viral replication", 0.85],
    ["burning pain", "central sensitization", 0.60],
    ["oral ulcers", "viral replication", 0.75],
    ["vesicular rash on hands", "viral replication", 0.80],
    ["vesicular rash on feet", "viral replication", 0.80],

    // DERMATOLOGIC SYMPTOMS
    ["itchy skin", "epidermal barrier disruption", 0.80],
    ["itchy skin", "IgE-mediated hypersensitivity", 0.60],
    ["dry skin", "epidermal barrier disruption", 0.85],
    ["red patches", "dermal inflammatory infiltrate", 0.75],
    ["skin thickening", "epidermal barrier disruption", 0.65],
    ["oozing", "epidermal barrier disruption", 0.60],
    ["cracking skin", "epidermal barrier disruption", 0.70],
    ["silvery scales", "keratinocyte hyperproliferation", 0.90],
    ["erythematous plaques", "keratinocyte hyperproliferation", 0.85],
    ["erythematous plaques", "dermal inflammatory infiltrate", 0.65],
    ["itching", "IgE-mediated hypersensitivity", 0.55],
    ["itching", "dermal inflammatory infiltrate", 0.55],
    ["nail pitting", "keratinocyte hyperproliferation", 0.70],
    ["Auspitz sign", "keratinocyte hyperproliferation", 0.85],
    ["Koebner phenomenon", "keratinocyte hyperproliferation", 0.75],
    ["wheals", "urticarial vasodilation", 0.95],
    ["wheals", "mast cell degranulation", 0.85],
    ["angioedema", "mast cell degranulation", 0.80],
    ["angioedema", "anaphylactic cascade", 0.70],
    ["urticaria", "urticarial vasodilation", 0.85],
    ["urticaria", "mast cell degranulation", 0.80],
    ["urticaria", "IgE-mediated hypersensitivity", 0.70],
    ["comedones", "follicular obstruction", 0.90],
    ["papules", "follicular obstruction", 0.75],
    ["pustules", "follicular obstruction", 0.70],
    ["oily skin", "sebaceous gland hyperactivity", 0.80],
    ["ring-shaped rash", "fungal colonization", 0.85],
    ["scaly patches", "fungal colonization", 0.70],
    ["scaly patches", "epidermal barrier disruption", 0.55],
    ["intense itching worse at night", "parasitic skin infestation", 0.90],
    ["burrows", "parasitic skin infestation", 0.90],
    ["web space lesions", "parasitic skin infestation", 0.80],
    ["asymmetric mole", "melanocyte dysplasia", 0.80],
    ["irregular borders", "melanocyte dysplasia", 0.80],
    ["color variation", "melanocyte dysplasia", 0.80],
    ["evolving lesion", "melanocyte dysplasia", 0.75],
    ["bleeding from mole", "melanocyte dysplasia", 0.70],
    ["erythema nodosum", "subcutaneous fat inflammation", 0.85],
    ["skin lesions", "granulomatous inflammation", 0.45],
    ["non-healing ulcers", "peripheral vascular insufficiency", 0.75],
    ["non-healing ulcers", "wound healing impairment", 0.80],
    ["scarring", "dermal fibrosis", 0.70],
    ["vesicles", "vesicle formation", 0.85],
    ["blistering", "vesicle formation", 0.80],
    ["dermatitis herpetiformis", "IgE-mediated hypersensitivity", 0.50],
    ["dermatitis herpetiformis", "malabsorption", 0.60],
    ["purulent discharge", "dermal inflammatory infiltrate", 0.70],
    ["eye redness", "dermal inflammatory infiltrate", 0.40],
    ["lip swelling", "mast cell degranulation", 0.75],

    // MUSCULOSKELETAL SYMPTOMS
    ["joint pain", "synovial inflammation", 0.65],
    ["joint stiffness", "synovial inflammation", 0.70],
    ["joint stiffness", "cartilage degeneration", 0.65],
    ["morning stiffness >1 hour", "synovial inflammation", 0.80],
    ["stiffness worse in morning", "cartilage degeneration", 0.65],
    ["joint swelling", "synovial inflammation", 0.80],
    ["joint swelling", "crystal arthropathy", 0.70],
    ["joint redness", "crystal arthropathy", 0.80],
    ["warmth over joint", "crystal arthropathy", 0.75],
    ["warmth over joint", "synovial inflammation", 0.70],
    ["crepitus", "cartilage degeneration", 0.80],
    ["decreased range of motion", "cartilage degeneration", 0.70],
    ["bony enlargement", "cartilage degeneration", 0.70],
    ["first MTP joint involvement", "crystal arthropathy", 0.80],
    ["tophi", "crystal arthropathy", 0.90],
    ["lower back pain", "muscle spasm physiology", 0.65],
    ["lower back pain", "intervertebral disc degeneration", 0.70],
    ["back pain", "intervertebral disc degeneration", 0.60],
    ["back pain", "muscle spasm physiology", 0.55],
    ["back pain", "nerve root compression", 0.50],
    ["muscle spasm", "muscle spasm physiology", 0.90],
    ["pain with movement", "muscle spasm physiology", 0.65],
    ["paraspinal tenderness", "muscle spasm physiology", 0.75],
    ["widespread pain", "central sensitization", 0.80],
    ["widespread pain", "myofascial pain", 0.70],
    ["tender points", "central sensitization", 0.80],
    ["tender points", "myofascial pain", 0.75],
    ["bone pain", "bone mineral loss", 0.55],
    ["bone pain", "bone fracture physiology", 0.50],
    ["bone pain", "chronic low-grade inflammation", 0.30],
    ["loss of height", "bone mineral loss", 0.70],
    ["fragility fracture", "bone mineral loss", 0.85],
    ["rheumatoid nodules", "synovial inflammation", 0.70],
    ["hand joint involvement", "synovial inflammation", 0.75],
    ["severe bone pain", "hemoglobin polymerization", 0.75],
    ["severe bone pain", "bone fracture physiology", 0.60],
    ["scalp tenderness", "myofascial pain", 0.60],
    ["muscle weakness", "cortisol excess", 0.45],
    ["muscle weakness", "thyroid hormone deficiency", 0.45],
    ["weakness", "iron depletion", 0.55],
    ["weakness", "cortisol deficiency", 0.45],
    ["exercise intolerance", "cardiac output reduction", 0.65],
    ["exercise intolerance", "iron depletion", 0.50],

    // HEMATOLOGIC SYMPTOMS
    ["pallor", "iron depletion", 0.80],
    ["pallor", "impaired erythropoiesis", 0.70],
    ["pallor", "hemolysis", 0.55],
    ["brittle nails", "iron depletion", 0.70],
    ["koilonychia", "iron depletion", 0.85],
    ["glossitis", "iron depletion", 0.65],
    ["glossitis", "megaloblastic erythropoiesis", 0.70],
    ["pica", "iron depletion", 0.75],
    ["easy bruising", "platelet consumption", 0.60],
    ["easy bruising", "hepatic fibrosis", 0.50],
    ["iron deficiency anemia", "iron depletion", 0.95],
    ["iron deficiency anemia", "chronic blood loss", 0.75],
    ["thrombocytopenia", "platelet consumption", 0.80],
    ["swelling hands feet", "hemoglobin polymerization", 0.70],
    ["splinter hemorrhages", "microvascular thrombosis", 0.70],
    ["Janeway lesions", "microvascular thrombosis", 0.75],
    ["Osler nodes", "immune complex deposition", 0.70],

    // PSYCHIATRIC SYMPTOMS
    ["depressed mood", "neuroinflammation", 0.35],
    ["loss of interest", "neuroinflammation", 0.30],
    ["sleep disturbance", "autonomic dysregulation", 0.40],
    ["depression", "neuroinflammation", 0.35],
    ["anxiety", "autonomic dysregulation", 0.50],
    ["excessive worry", "autonomic dysregulation", 0.55],
    ["restlessness", "autonomic dysregulation", 0.50],
    ["irritability", "neuroinflammation", 0.30],
    ["agitation", "thyroid hormone excess", 0.45],
    ["agitation", "neuroinflammation", 0.35],
    ["sudden intense fear", "autonomic dysregulation", 0.65],
    ["difficulty concentrating", "neuroinflammation", 0.30],
    ["suicidal ideation", "neuroinflammation", 0.25],
    ["personality changes", "neurodegenerative protein aggregation", 0.55],
    ["excessive daytime sleepiness", "autonomic dysregulation", 0.50],
    ["unrefreshing sleep", "central sensitization", 0.45],
    ["cognitive dysfunction", "central sensitization", 0.50],
    ["memory problems", "megaloblastic erythropoiesis", 0.40],

    // ENT/OPHTHALMOLOGIC SYMPTOMS  
    ["ear pain", "pharyngeal inflammation", 0.40],
    ["ear pain", "dermal inflammatory infiltrate", 0.35],
    ["hearing loss", "vestibular dysfunction", 0.45],
    ["ear discharge", "dermal inflammatory infiltrate", 0.50],
    ["tinnitus", "vestibular dysfunction", 0.75],
    ["aural fullness", "vestibular dysfunction", 0.70],
    ["fluctuating hearing loss", "vestibular dysfunction", 0.80],
    ["itchy eyes", "IgE-mediated hypersensitivity", 0.80],
    ["watery eyes", "IgE-mediated hypersensitivity", 0.75],
    ["red eyes", "IgE-mediated hypersensitivity", 0.55],
    ["red eyes", "dermal inflammatory infiltrate", 0.45],
    ["severe eye pain", "intracranial pressure elevation", 0.50],
    ["halos around lights", "intracranial pressure elevation", 0.50],
    ["gradual vision loss", "intracranial pressure elevation", 0.40],
    ["tunnel vision", "intracranial pressure elevation", 0.45],
    ["gradual blurred vision", "calcium homeostasis disruption", 0.20],
    ["glare sensitivity", "calcium homeostasis disruption", 0.15],
    ["taste changes", "facial nerve paralysis", 0.60],
    ["hyperacusis", "facial nerve paralysis", 0.55],
    ["snoring", "airway obstruction", 0.70],
    ["witnessed apneas", "airway obstruction", 0.80],
    ["facial pain", "sinusoidal mucosal inflammation", 0.80],
    ["facial pressure", "sinusoidal mucosal inflammation", 0.80],
    ["dental pain", "sinusoidal mucosal inflammation", 0.40],
    ["voice loss", "laryngeal inflammation", 0.80],
    ["throat clearing", "laryngeal inflammation", 0.55],
    ["tickling in throat", "pharyngeal inflammation", 0.50],
    ["pain with ear traction", "dermal inflammatory infiltrate", 0.70],
    ["ear canal itching", "dermal inflammatory infiltrate", 0.60],
    ["ear canal swelling", "dermal inflammatory infiltrate", 0.65],
    ["irritability in children", "systemic inflammatory response", 0.30],
    ["pulling at ear", "dermal inflammatory infiltrate", 0.40],
    ["triggered by head movement", "vestibular dysfunction", 0.85],
    ["imbalance", "vestibular dysfunction", 0.65],
    ["balance problems", "vestibular dysfunction", 0.65],
    ["balance problems", "demyelination", 0.50],

    // OBSTETRIC/EMERGENCY
    ["vaginal bleeding", "ectopic implantation", 0.60],
    ["vaginal bleeding", "placental dysfunction", 0.55],
    ["missed period", "ectopic implantation", 0.55],
    ["shoulder pain", "peritoneal irritation", 0.40],
    ["hypertension in pregnancy", "placental dysfunction", 0.80],
    ["rapid weight gain", "placental dysfunction", 0.50],
    ["hyperthermia >40C", "systemic inflammatory response", 0.70],
    ["hot dry skin", "autonomic dysregulation", 0.55],
    ["absence of sweating", "autonomic dysregulation", 0.60],

    // GENERAL/CROSS-SYSTEM
    ["weight loss", "cell-mediated immune response", 0.40],
    ["night sweats", "cell-mediated immune response", 0.55],
    ["respiratory failure", "hypoxemic respiratory failure", 0.95],
    ["respiratory distress", "respiratory muscle fatigue", 0.70],
    ["respiratory difficulty", "ascending paralysis", 0.65],
    ["difficulty speaking", "bronchoconstriction", 0.55],
    ["nosebleed", "increased systemic vascular resistance", 0.40],
    ["visual changes", "increased systemic vascular resistance", 0.45],
    ["visual disturbance", "demyelination", 0.60],
    ["urinary dysfunction", "demyelination", 0.50],
    ["urinary incontinence", "seizure activity", 0.45],
    ["tongue biting", "seizure activity", 0.70],
    ["automatisms", "seizure activity", 0.65],
    ["aura", "seizure activity", 0.60],
    ["confusion post-ictal", "seizure activity", 0.80],
    ["dropping objects", "peripheral nerve compression", 0.55],
    ["nocturnal paresthesias", "peripheral nerve compression", 0.75],
    ["recent viral illness", "myocardial inflammation", 0.55],
    ["tripod position", "upper airway edema", 0.70],
    ["apnea in infants", "airway inflammation", 0.60],
    ["Homan sign", "venous thrombosis", 0.50],
    ["coryza", "nasal mucosal inflammation", 0.80],
    ["pain triggered by touch", "trigeminal nerve irritation", 0.80],
    ["pain triggered by chewing", "trigeminal nerve irritation", 0.70],
    ["pain episodes lasting seconds", "trigeminal nerve irritation", 0.75],
    ["stooped posture", "bone mineral loss", 0.60],
    ["hair loss on legs", "peripheral vascular insufficiency", 0.55],
    ["leg heaviness", "venous valve incompetence", 0.70],
    ["leg aching", "venous valve incompetence", 0.65],
    ["leg cramps", "venous valve incompetence", 0.50],
    ["itching over veins", "venous valve incompetence", 0.55],
    ["wandering", "neurodegenerative protein aggregation", 0.55],
    ["micrographia", "dopaminergic depletion", 0.75],
    ["masked facies", "dopaminergic depletion", 0.75],
    ["pulsatile abdominal mass", "aortic wall degeneration", 0.85],
    ["bilateral hilar lymphadenopathy", "granulomatous inflammation", 0.80],
    ["failure to thrive in children", "malabsorption", 0.60],
    ["infertility", "ovarian follicular dysfunction", 0.65],
    ["pelvic pain", "ovarian follicular dysfunction", 0.40],
    ["Koplik spots", "viral replication", 0.90],
    ["rose spots", "bacterial toxin release", 0.70],
    ["relative bradycardia", "bacterial toxin release", 0.55],
    ["often asymptomatic", "chronic low-grade inflammation", 0.20],
    ["chest discomfort", "myocardial ischemia", 0.55],
    ["chest discomfort", "gastroesophageal reflux", 0.40],
    ["pain relieved by eating", "gastric mucosal erosion", 0.60],
    ["pain worse on empty stomach", "gastric mucosal erosion", 0.65],
    ["change in bowel habits", "colonic dysmotility", 0.55],
    ["change in bowel habits", "colonic mucosal ulceration", 0.50],
    ["narrow stools", "colonic mucosal ulceration", 0.45],
    ["altered bowel habits", "visceral hypersensitivity", 0.60],
    ["altered bowel habits", "colonic dysmotility", 0.55],
    ["abdominal bloating", "intestinal motility dysfunction", 0.65],
    ["abdominal bloating", "malabsorption", 0.55],
  ];
}

// ── PHYSIOLOGY → DISEASE MAPPINGS ──
// [physiology_state_name, disease_name, strength]
type PhysioDx = [string, string, number];

function generatePhysiologyDiseaseMap(): PhysioDx[] {
  return [
    // RESPIRATORY
    ["airway inflammation", "influenza", 0.70],
    ["airway inflammation", "COVID-19", 0.70],
    ["airway inflammation", "acute bronchitis", 0.85],
    ["airway inflammation", "community-acquired pneumonia", 0.75],
    ["airway inflammation", "pertussis", 0.80],
    ["airway inflammation", "croup", 0.80],
    ["bronchoconstriction", "asthma exacerbation", 0.90],
    ["bronchoconstriction", "COPD exacerbation", 0.80],
    ["bronchoconstriction", "anaphylaxis", 0.70],
    ["bronchial hyperreactivity", "asthma exacerbation", 0.90],
    ["bronchial hyperreactivity", "allergic rhinitis", 0.40],
    ["alveolar damage", "community-acquired pneumonia", 0.75],
    ["alveolar damage", "acute respiratory distress syndrome", 0.90],
    ["alveolar damage", "COVID pneumonia", 0.85],
    ["mucus hypersecretion", "acute bronchitis", 0.80],
    ["mucus hypersecretion", "COPD exacerbation", 0.85],
    ["mucus hypersecretion", "bronchiectasis", 0.90],
    ["mucus hypersecretion", "croup", 0.55],
    ["pulmonary vascular congestion", "congestive heart failure", 0.85],
    ["pulmonary vascular congestion", "pulmonary embolism", 0.50],
    ["airway obstruction", "COPD exacerbation", 0.85],
    ["airway obstruction", "obstructive sleep apnea", 0.85],
    ["airway obstruction", "acute epiglottitis", 0.80],
    ["pharyngeal inflammation", "strep throat", 0.85],
    ["pharyngeal inflammation", "acute tonsillitis", 0.85],
    ["pharyngeal inflammation", "acute pharyngitis", 0.90],
    ["pharyngeal inflammation", "infectious mononucleosis", 0.65],
    ["nasal mucosal inflammation", "allergic rhinitis", 0.90],
    ["nasal mucosal inflammation", "acute sinusitis", 0.70],
    ["nasal mucosal inflammation", "influenza", 0.55],
    ["pleural inflammation", "pleural effusion", 0.80],
    ["pleural inflammation", "community-acquired pneumonia", 0.55],
    ["pleural inflammation", "tuberculosis", 0.50],
    ["pulmonary fibrosis", "interstitial lung disease", 0.90],
    ["pulmonary fibrosis", "sarcoidosis", 0.55],
    ["ventilation-perfusion mismatch", "pulmonary embolism", 0.85],
    ["ventilation-perfusion mismatch", "COPD exacerbation", 0.70],
    ["ventilation-perfusion mismatch", "community-acquired pneumonia", 0.65],
    ["respiratory muscle fatigue", "COPD exacerbation", 0.60],
    ["respiratory muscle fatigue", "Guillain-Barré syndrome", 0.65],
    ["upper airway edema", "croup", 0.90],
    ["upper airway edema", "acute epiglottitis", 0.90],
    ["upper airway edema", "anaphylaxis", 0.80],
    ["upper airway edema", "peritonsillar abscess", 0.70],
    ["pulmonary hypertension", "COPD exacerbation", 0.50],
    ["pulmonary hypertension", "pulmonary embolism", 0.60],
    ["pulmonary hypertension", "interstitial lung disease", 0.55],
    ["atelectasis", "pleural effusion", 0.55],
    ["atelectasis", "pneumothorax", 0.60],
    ["laryngeal inflammation", "laryngitis", 0.90],
    ["laryngeal inflammation", "croup", 0.80],
    ["sinusoidal mucosal inflammation", "acute sinusitis", 0.90],
    ["sinusoidal mucosal inflammation", "chronic sinusitis", 0.90],
    ["pulmonary parenchymal necrosis", "lung abscess", 0.85],
    ["pulmonary parenchymal necrosis", "tuberculosis", 0.70],
    ["ciliary dysfunction", "bronchiectasis", 0.70],
    ["surfactant deficiency", "acute respiratory distress syndrome", 0.75],
    ["bronchiolar destruction", "COPD exacerbation", 0.85],
    ["bronchiolar destruction", "bronchiectasis", 0.80],
    ["pulmonary edema", "congestive heart failure", 0.85],
    ["pulmonary edema", "acute respiratory distress syndrome", 0.80],
    ["pneumothorax physiology", "pneumothorax", 0.95],
    ["hypoxemic respiratory failure", "acute respiratory distress syndrome", 0.90],
    ["hypoxemic respiratory failure", "COVID pneumonia", 0.80],
    ["hypoxemic respiratory failure", "community-acquired pneumonia", 0.65],

    // CARDIOVASCULAR
    ["myocardial ischemia", "acute myocardial infarction", 0.90],
    ["myocardial ischemia", "unstable angina", 0.85],
    ["myocardial necrosis", "acute myocardial infarction", 0.95],
    ["cardiac arrhythmia", "atrial fibrillation", 0.85],
    ["cardiac arrhythmia", "supraventricular tachycardia", 0.85],
    ["left ventricular systolic dysfunction", "congestive heart failure", 0.90],
    ["left ventricular diastolic dysfunction", "congestive heart failure", 0.75],
    ["vascular endothelial dysfunction", "essential hypertension", 0.65],
    ["vascular endothelial dysfunction", "peripheral artery disease", 0.60],
    ["atherosclerotic plaque formation", "acute myocardial infarction", 0.75],
    ["atherosclerotic plaque formation", "peripheral artery disease", 0.80],
    ["atherosclerotic plaque formation", "acute ischemic stroke", 0.70],
    ["increased systemic vascular resistance", "essential hypertension", 0.85],
    ["increased systemic vascular resistance", "hypertensive crisis", 0.90],
    ["venous thrombosis", "deep vein thrombosis", 0.90],
    ["venous thrombosis", "pulmonary embolism", 0.75],
    ["cardiac valve dysfunction", "aortic stenosis", 0.85],
    ["cardiac valve dysfunction", "mitral valve prolapse", 0.80],
    ["cardiac valve dysfunction", "infective endocarditis", 0.65],
    ["pericardial inflammation", "pericarditis", 0.90],
    ["cardiac conduction block", "atrial fibrillation", 0.50],
    ["aortic wall degeneration", "aortic dissection", 0.90],
    ["aortic wall degeneration", "abdominal aortic aneurysm", 0.85],
    ["peripheral vascular insufficiency", "peripheral artery disease", 0.90],
    ["venous valve incompetence", "varicose veins", 0.90],
    ["venous valve incompetence", "deep vein thrombosis", 0.40],
    ["cardiac tamponade physiology", "cardiac tamponade", 0.95],
    ["right heart failure", "congestive heart failure", 0.70],
    ["right heart failure", "pulmonary embolism", 0.55],
    ["coronary vasospasm", "unstable angina", 0.70],
    ["myocardial inflammation", "myocarditis", 0.90],
    ["cardiac output reduction", "congestive heart failure", 0.80],
    ["cardiac output reduction", "cardiac tamponade", 0.75],
    ["cardiac output reduction", "aortic stenosis", 0.65],
    ["fluid overload", "congestive heart failure", 0.80],
    ["fluid overload", "chronic kidney disease", 0.65],
    ["fluid overload", "nephrotic syndrome", 0.55],
    ["systemic hypoperfusion", "sepsis", 0.80],
    ["systemic hypoperfusion", "acute myocardial infarction", 0.55],
    ["vasodilatory shock", "sepsis", 0.85],
    ["vasodilatory shock", "anaphylaxis", 0.80],
    ["microvascular thrombosis", "infective endocarditis", 0.65],
    ["microvascular thrombosis", "disseminated intravascular coagulation", 0.80],

    // NEUROLOGICAL
    ["neuroinflammation", "meningitis", 0.75],
    ["neuroinflammation", "multiple sclerosis", 0.65],
    ["meningeal irritation", "meningitis", 0.90],
    ["meningeal irritation", "subarachnoid hemorrhage", 0.80],
    ["cortical spreading depression", "migraine", 0.90],
    ["cerebral ischemia", "acute ischemic stroke", 0.90],
    ["cerebral ischemia", "transient ischemic attack", 0.80],
    ["intracranial pressure elevation", "meningitis", 0.55],
    ["intracranial pressure elevation", "subarachnoid hemorrhage", 0.65],
    ["intracranial pressure elevation", "acute angle-closure glaucoma", 0.40],
    ["demyelination", "multiple sclerosis", 0.90],
    ["peripheral nerve compression", "carpal tunnel syndrome", 0.90],
    ["dopaminergic depletion", "Parkinson disease", 0.90],
    ["seizure activity", "epilepsy", 0.90],
    ["cerebral hemorrhage", "subarachnoid hemorrhage", 0.90],
    ["peripheral neuropathy", "type 2 diabetes mellitus", 0.55],
    ["peripheral neuropathy", "vitamin B12 deficiency", 0.65],
    ["peripheral neuropathy", "Guillain-Barré syndrome", 0.60],
    ["central sensitization", "fibromyalgia", 0.85],
    ["central sensitization", "tension-type headache", 0.55],
    ["trigeminal nerve irritation", "trigeminal neuralgia", 0.90],
    ["facial nerve paralysis", "Bell palsy", 0.90],
    ["vestibular dysfunction", "benign paroxysmal positional vertigo", 0.85],
    ["vestibular dysfunction", "Meniere disease", 0.85],
    ["cholinergic deficit", "Alzheimer disease", 0.85],
    ["ascending paralysis", "Guillain-Barré syndrome", 0.90],
    ["neurodegenerative protein aggregation", "Alzheimer disease", 0.85],
    ["neurodegenerative protein aggregation", "Parkinson disease", 0.50],
    ["nerve root compression", "lumbar disc herniation", 0.90],
    ["nerve root compression", "low back pain", 0.45],
    ["spinal cord compression", "lumbar disc herniation", 0.50],
    ["autonomic dysregulation", "Guillain-Barré syndrome", 0.45],
    ["autonomic dysregulation", "Parkinson disease", 0.40],
    ["blood-brain barrier disruption", "meningitis", 0.70],
    ["cerebral vasospasm", "subarachnoid hemorrhage", 0.80],
    ["muscle spasm physiology", "low back pain", 0.70],
    ["myofascial pain", "tension-type headache", 0.75],
    ["myofascial pain", "fibromyalgia", 0.65],

    // GASTROINTESTINAL
    ["gastric mucosal erosion", "peptic ulcer disease", 0.90],
    ["gastric mucosal erosion", "acute gastritis", 0.85],
    ["gastric mucosal erosion", "gastric cancer", 0.40],
    ["intestinal inflammation", "acute gastroenteritis", 0.80],
    ["intestinal inflammation", "inflammatory bowel disease - Crohn's", 0.85],
    ["intestinal inflammation", "ulcerative colitis", 0.85],
    ["intestinal inflammation", "celiac disease", 0.70],
    ["hepatocellular injury", "acute hepatitis", 0.85],
    ["hepatocellular injury", "liver cirrhosis", 0.70],
    ["hepatocellular injury", "hepatitis A", 0.80],
    ["hepatocellular injury", "hepatitis B", 0.80],
    ["biliary obstruction", "choledocholithiasis", 0.90],
    ["biliary obstruction", "acute cholecystitis", 0.65],
    ["biliary obstruction", "acute hepatitis", 0.40],
    ["pancreatic acinar cell injury", "acute pancreatitis", 0.90],
    ["intestinal motility dysfunction", "irritable bowel syndrome", 0.80],
    ["intestinal motility dysfunction", "small bowel obstruction", 0.55],
    ["gastroesophageal reflux", "gastroesophageal reflux disease", 0.90],
    ["peritoneal irritation", "acute appendicitis", 0.85],
    ["peritoneal irritation", "acute cholecystitis", 0.65],
    ["peritoneal irritation", "diverticulitis", 0.70],
    ["peritoneal irritation", "acute pancreatitis", 0.55],
    ["hepatic fibrosis", "liver cirrhosis", 0.90],
    ["portal hypertension", "liver cirrhosis", 0.85],
    ["visceral hypersensitivity", "irritable bowel syndrome", 0.85],
    ["malabsorption", "celiac disease", 0.85],
    ["malabsorption", "inflammatory bowel disease - Crohn's", 0.55],
    ["intestinal obstruction", "small bowel obstruction", 0.90],
    ["gallbladder inflammation", "acute cholecystitis", 0.90],
    ["colonic mucosal ulceration", "ulcerative colitis", 0.90],
    ["colonic mucosal ulceration", "colorectal cancer", 0.45],
    ["appendiceal obstruction", "acute appendicitis", 0.90],
    ["diverticular inflammation", "diverticulitis", 0.90],
    ["helicobacter pylori infection", "peptic ulcer disease", 0.80],
    ["helicobacter pylori infection", "acute gastritis", 0.70],
    ["hepatic encephalopathy", "liver cirrhosis", 0.75],
    ["gastrointestinal hemorrhage", "peptic ulcer disease", 0.65],
    ["gastrointestinal hemorrhage", "colorectal cancer", 0.50],
    ["gastrointestinal hemorrhage", "liver cirrhosis", 0.50],
    ["esophageal dysmotility", "gastroesophageal reflux disease", 0.50],
    ["colonic dysmotility", "irritable bowel syndrome", 0.65],
    ["bacterial overgrowth", "irritable bowel syndrome", 0.40],
    ["mesenteric ischemia", "small bowel obstruction", 0.35],
    ["intestinal barrier disruption", "celiac disease", 0.65],

    // ENDOCRINE
    ["insulin resistance", "type 2 diabetes mellitus", 0.90],
    ["insulin resistance", "polycystic ovary syndrome", 0.65],
    ["insulin resistance", "obesity", 0.70],
    ["insulin deficiency", "type 1 diabetes mellitus", 0.90],
    ["insulin deficiency", "diabetic ketoacidosis", 0.85],
    ["thyroid hormone deficiency", "hypothyroidism", 0.90],
    ["thyroid hormone excess", "hyperthyroidism", 0.90],
    ["thyroid hormone excess", "thyroid storm", 0.85],
    ["cortisol excess", "Cushing syndrome", 0.90],
    ["cortisol deficiency", "Addison disease", 0.90],
    ["hyperandrogenism", "polycystic ovary syndrome", 0.85],
    ["diabetic ketoacidosis physiology", "diabetic ketoacidosis", 0.95],
    ["diabetic ketoacidosis physiology", "type 1 diabetes mellitus", 0.55],
    ["metabolic acidosis", "diabetic ketoacidosis", 0.80],
    ["metabolic acidosis", "acute kidney injury", 0.55],
    ["metabolic acidosis", "sepsis", 0.50],
    ["hyperglycemia", "type 2 diabetes mellitus", 0.85],
    ["hyperglycemia", "type 1 diabetes mellitus", 0.80],
    ["hyperglycemia", "diabetic ketoacidosis", 0.75],
    ["hypoglycemia", "type 1 diabetes mellitus", 0.40],
    ["electrolyte imbalance", "acute kidney injury", 0.60],
    ["electrolyte imbalance", "diabetic ketoacidosis", 0.55],
    ["thyroid autoimmunity", "hypothyroidism", 0.70],
    ["thyroid autoimmunity", "hyperthyroidism", 0.65],
    ["calcium homeostasis disruption", "osteoporosis", 0.50],
    ["ovarian follicular dysfunction", "polycystic ovary syndrome", 0.85],
    ["gonadal dysfunction", "polycystic ovary syndrome", 0.50],

    // RENAL
    ["glomerular filtration impairment", "acute kidney injury", 0.85],
    ["glomerular filtration impairment", "chronic kidney disease", 0.90],
    ["tubular necrosis", "acute kidney injury", 0.80],
    ["nephrotic protein loss", "nephrotic syndrome", 0.95],
    ["renal interstitial inflammation", "pyelonephritis", 0.85],
    ["urinary tract mucosal inflammation", "urinary tract infection", 0.90],
    ["urinary tract mucosal inflammation", "pyelonephritis", 0.55],
    ["renal calculus obstruction", "nephrolithiasis", 0.90],
    ["glomerulonephritis", "glomerulonephritis", 0.95],
    ["prerenal azotemia", "acute kidney injury", 0.70],
    ["prerenal azotemia", "congestive heart failure", 0.45],
    ["sodium retention", "chronic kidney disease", 0.65],
    ["sodium retention", "congestive heart failure", 0.60],
    ["potassium homeostasis disruption", "acute kidney injury", 0.55],
    ["potassium homeostasis disruption", "chronic kidney disease", 0.55],
    ["obstructive uropathy", "nephrolithiasis", 0.55],

    // IMMUNE/INFECTIOUS
    ["systemic inflammatory response", "sepsis", 0.85],
    ["systemic inflammatory response", "influenza", 0.55],
    ["systemic inflammatory response", "COVID-19", 0.60],
    ["systemic inflammatory response", "dengue fever", 0.65],
    ["systemic inflammatory response", "malaria", 0.65],
    ["systemic inflammatory response", "typhoid fever", 0.65],
    ["IgE-mediated hypersensitivity", "allergic rhinitis", 0.85],
    ["IgE-mediated hypersensitivity", "allergic conjunctivitis", 0.80],
    ["IgE-mediated hypersensitivity", "urticaria", 0.80],
    ["IgE-mediated hypersensitivity", "anaphylaxis", 0.75],
    ["IgE-mediated hypersensitivity", "food allergy", 0.80],
    ["immune complex deposition", "glomerulonephritis", 0.65],
    ["immune complex deposition", "infective endocarditis", 0.50],
    ["cell-mediated immune response", "tuberculosis", 0.80],
    ["cell-mediated immune response", "sarcoidosis", 0.70],
    ["granulomatous inflammation", "tuberculosis", 0.75],
    ["granulomatous inflammation", "sarcoidosis", 0.85],
    ["mast cell degranulation", "anaphylaxis", 0.90],
    ["mast cell degranulation", "urticaria", 0.80],
    ["mast cell degranulation", "drug allergy reaction", 0.70],
    ["anaphylactic cascade", "anaphylaxis", 0.95],
    ["viral replication", "influenza", 0.80],
    ["viral replication", "COVID-19", 0.85],
    ["viral replication", "dengue fever", 0.80],
    ["viral replication", "chickenpox", 0.85],
    ["viral replication", "herpes zoster", 0.85],
    ["viral replication", "measles", 0.85],
    ["viral replication", "mumps", 0.85],
    ["viral replication", "infectious mononucleosis", 0.80],
    ["viral replication", "hand foot and mouth disease", 0.80],
    ["viral replication", "hepatitis A", 0.70],
    ["viral replication", "hepatitis B", 0.70],
    ["bacterial toxin release", "strep throat", 0.75],
    ["bacterial toxin release", "typhoid fever", 0.70],
    ["bacterial toxin release", "cellulitis", 0.55],
    ["bacterial toxin release", "acute gastroenteritis", 0.65],
    ["sepsis cascade", "sepsis", 0.95],
    ["immune deficiency", "HIV/AIDS", 0.90],
    ["autoimmune tissue destruction", "rheumatoid arthritis", 0.75],
    ["autoimmune tissue destruction", "multiple sclerosis", 0.70],
    ["autoimmune tissue destruction", "type 1 diabetes mellitus", 0.65],
    ["cytokine storm", "COVID pneumonia", 0.75],
    ["cytokine storm", "sepsis", 0.70],
    ["parasitic tissue invasion", "malaria", 0.85],
    ["fungal colonization", "fungal skin infection", 0.85],
    ["lymphoid hyperplasia", "infectious mononucleosis", 0.75],
    ["lymphoid hyperplasia", "HIV/AIDS", 0.55],
    ["lymphoid hyperplasia", "strep throat", 0.50],
    ["type IV hypersensitivity", "drug allergy reaction", 0.65],
    ["chronic low-grade inflammation", "obesity", 0.50],
    ["chronic low-grade inflammation", "type 2 diabetes mellitus", 0.45],
    ["complement activation", "sepsis", 0.45],

    // DERMATOLOGIC
    ["epidermal barrier disruption", "eczema", 0.90],
    ["keratinocyte hyperproliferation", "psoriasis", 0.90],
    ["dermal inflammatory infiltrate", "cellulitis", 0.75],
    ["dermal inflammatory infiltrate", "eczema", 0.65],
    ["melanocyte dysplasia", "melanoma", 0.90],
    ["sebaceous gland hyperactivity", "acne vulgaris", 0.85],
    ["urticarial vasodilation", "urticaria", 0.90],
    ["parasitic skin infestation", "scabies", 0.90],
    ["follicular obstruction", "acne vulgaris", 0.85],
    ["subcutaneous fat inflammation", "sarcoidosis", 0.40],
    ["vesicle formation", "chickenpox", 0.70],
    ["vesicle formation", "herpes zoster", 0.70],
    ["wound healing impairment", "type 2 diabetes mellitus", 0.45],

    // MUSCULOSKELETAL
    ["synovial inflammation", "rheumatoid arthritis", 0.85],
    ["synovial inflammation", "gout", 0.60],
    ["cartilage degeneration", "osteoarthritis", 0.90],
    ["crystal arthropathy", "gout", 0.90],
    ["intervertebral disc degeneration", "lumbar disc herniation", 0.80],
    ["intervertebral disc degeneration", "low back pain", 0.65],
    ["bone mineral loss", "osteoporosis", 0.90],
    ["enthesopathy", "psoriasis", 0.40],
    ["spinal stenosis", "low back pain", 0.50],
    ["osteoarticular infection", "sepsis", 0.30],

    // HEMATOLOGIC
    ["iron depletion", "iron deficiency anemia", 0.95],
    ["megaloblastic erythropoiesis", "vitamin B12 deficiency", 0.90],
    ["hemoglobin polymerization", "sickle cell crisis", 0.95],
    ["coagulation cascade activation", "deep vein thrombosis", 0.70],
    ["coagulation cascade activation", "pulmonary embolism", 0.65],
    ["platelet consumption", "dengue fever", 0.60],
    ["platelet consumption", "sepsis", 0.45],
    ["disseminated intravascular coagulation", "sepsis", 0.55],
    ["hemolysis", "malaria", 0.60],
    ["hemolysis", "sickle cell crisis", 0.55],
    ["impaired erythropoiesis", "chronic kidney disease", 0.55],
    ["hypercoagulable state", "deep vein thrombosis", 0.65],
    ["hypercoagulable state", "pulmonary embolism", 0.60],
    ["chronic blood loss", "iron deficiency anemia", 0.70],
    ["chronic blood loss", "colorectal cancer", 0.45],

    // REPRODUCTIVE/OBSTETRIC
    ["ectopic implantation", "ectopic pregnancy", 0.95],
    ["placental dysfunction", "preeclampsia", 0.90],
    ["ovarian follicular dysfunction", "polycystic ovary syndrome", 0.85],
    ["endometrial hyperplasia", "polycystic ovary syndrome", 0.40],
  ];
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
  const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
  const supabase = createClient(supabaseUrl, serviceKey);

  const log: string[] = [];
  const addLog = (msg: string) => { log.push(msg); console.log(msg); };

  try {
    const physioStates = generatePhysiologyStates();
    const symPhysio = generateSymptomPhysiologyMap();
    const physioDx = generatePhysiologyDiseaseMap();

    addLog(`Generated ${physioStates.length} physiology states`);
    addLog(`Generated ${symPhysio.length} symptom-physiology links`);
    addLog(`Generated ${physioDx.length} physiology-disease links`);

    // ── STEP 0: Ensure additional anatomical systems exist ──
    const neededSystems = new Set(physioStates.map(p => p[2]));
    const { data: existingSystems } = await supabase.from("anatomical_systems").select("id, system_name");
    const systemMap: Record<string, string> = {};
    for (const s of existingSystems || []) systemMap[s.system_name] = s.id;

    const missingSystems = [...neededSystems].filter(s => !systemMap[s]);
    if (missingSystems.length > 0) {
      addLog(`Adding ${missingSystems.length} missing anatomical systems: ${missingSystems.join(", ")}`);
      const { data: inserted, error } = await supabase.from("anatomical_systems").insert(
        missingSystems.map(s => ({ system_name: s, description: `${s} organ system` }))
      ).select("id, system_name");
      if (error) addLog(`  Error: ${error.message}`);
      if (inserted) for (const s of inserted) systemMap[s.system_name] = s.id;
    }
    addLog(`Total anatomical systems: ${Object.keys(systemMap).length}`);

    // ── STEP 1: Upsert physiological states ──
    addLog("Step 1: Upserting physiological states...");
    const stateRows = physioStates.filter(([, , sys]) => systemMap[sys]).map(([name, desc, sys]) => ({
      state_name: name,
      description: desc,
      system_id: systemMap[sys],
    }));
    for (let i = 0; i < stateRows.length; i += 100) {
      const chunk = stateRows.slice(i, i + 100);
      const { error } = await supabase.from("physiological_states").upsert(chunk, { onConflict: "state_name", ignoreDuplicates: true });
      if (error) addLog(`  States upsert error (batch ${i}): ${error.message}`);
    }
    addLog(`  Physiological states upserted: ${stateRows.length}`);

    // Fetch all state IDs
    const stateMap: Record<string, string> = {};
    let offset = 0;
    while (true) {
      const { data: batch } = await supabase.from("physiological_states").select("id, state_name").range(offset, offset + 999);
      if (!batch || batch.length === 0) break;
      for (const r of batch) stateMap[r.state_name] = r.id;
      offset += batch.length;
      if (batch.length < 1000) break;
    }
    addLog(`  Fetched ${Object.keys(stateMap).length} state IDs`);

    // ── Fetch all symptom IDs ──
    const symMap: Record<string, string> = {};
    offset = 0;
    while (true) {
      const { data: batch } = await supabase.from("symptoms").select("id, symptom_name").range(offset, offset + 999);
      if (!batch || batch.length === 0) break;
      for (const r of batch) symMap[r.symptom_name] = r.id;
      offset += batch.length;
      if (batch.length < 1000) break;
    }
    addLog(`  Fetched ${Object.keys(symMap).length} symptom IDs`);

    // ── Fetch all diagnosis IDs ──
    const diagMap: Record<string, string> = {};
    offset = 0;
    while (true) {
      const { data: batch } = await supabase.from("diagnoses").select("id, diagnosis_name").range(offset, offset + 999);
      if (!batch || batch.length === 0) break;
      for (const r of batch) diagMap[r.diagnosis_name] = r.id;
      offset += batch.length;
      if (batch.length < 1000) break;
    }
    addLog(`  Fetched ${Object.keys(diagMap).length} diagnosis IDs`);

    // ── STEP 2: Insert symptom_physiology_map ──
    addLog("Step 2: Inserting symptom-physiology links...");
    const symPhysioRows: { symptom_id: string; physiological_state_id: string; confidence_score: number }[] = [];
    let skippedSym = 0;
    for (const [sym, state, conf] of symPhysio) {
      const sId = symMap[sym];
      const pId = stateMap[state];
      if (!sId || !pId) { skippedSym++; continue; }
      symPhysioRows.push({ symptom_id: sId, physiological_state_id: pId, confidence_score: conf });
    }
    addLog(`  Matched: ${symPhysioRows.length}, Skipped (missing IDs): ${skippedSym}`);

    let symPhysioInserted = 0;
    for (let i = 0; i < symPhysioRows.length; i += 200) {
      const chunk = symPhysioRows.slice(i, i + 200);
      const { error } = await supabase.from("symptom_physiology_map").insert(chunk);
      if (error) {
        addLog(`  sym-physio insert error (batch ${i}): ${error.message}`);
      } else {
        symPhysioInserted += chunk.length;
      }
    }
    addLog(`  Symptom-physiology links inserted: ${symPhysioInserted}`);

    // ── STEP 3: Insert physiology_diagnosis_map ──
    addLog("Step 3: Inserting physiology-disease links...");
    const physioDxRows: { physiological_state_id: string; diagnosis_id: string; relevance_score: number }[] = [];
    let skippedDx = 0;
    for (const [state, dx, str] of physioDx) {
      const pId = stateMap[state];
      const dId = diagMap[dx];
      if (!pId || !dId) { skippedDx++; continue; }
      physioDxRows.push({ physiological_state_id: pId, diagnosis_id: dId, relevance_score: str });
    }
    addLog(`  Matched: ${physioDxRows.length}, Skipped (missing IDs): ${skippedDx}`);

    let physioDxInserted = 0;
    for (let i = 0; i < physioDxRows.length; i += 200) {
      const chunk = physioDxRows.slice(i, i + 200);
      const { error } = await supabase.from("physiology_diagnosis_map").insert(chunk);
      if (error) {
        addLog(`  physio-dx insert error (batch ${i}): ${error.message}`);
      } else {
        physioDxInserted += chunk.length;
      }
    }
    addLog(`  Physiology-disease links inserted: ${physioDxInserted}`);

    // ── STEP 4: Also populate physiology_likelihoods ──
    addLog("Step 4: Populating physiology_likelihoods...");
    const likelihoodRows: { physiological_state_id: string; diagnosis_id: string; likelihood_value: number }[] = [];
    for (const [state, dx, str] of physioDx) {
      const pId = stateMap[state];
      const dId = diagMap[dx];
      if (!pId || !dId) continue;
      likelihoodRows.push({ physiological_state_id: pId, diagnosis_id: dId, likelihood_value: str });
    }
    let likelihoodInserted = 0;
    for (let i = 0; i < likelihoodRows.length; i += 200) {
      const chunk = likelihoodRows.slice(i, i + 200);
      const { error } = await supabase.from("physiology_likelihoods").insert(chunk);
      if (error) {
        addLog(`  physio-likelihood insert error (batch ${i}): ${error.message}`);
      } else {
        likelihoodInserted += chunk.length;
      }
    }
    addLog(`  Physiology likelihoods inserted: ${likelihoodInserted}`);

    // ── VALIDATION ──
    addLog("=== VALIDATION ===");
    const { count: statesCount } = await supabase.from("physiological_states").select("*", { count: "exact", head: true });
    const { count: symPhysioCount } = await supabase.from("symptom_physiology_map").select("*", { count: "exact", head: true });
    const { count: physioDxCount } = await supabase.from("physiology_diagnosis_map").select("*", { count: "exact", head: true });
    const { count: physioLikCount } = await supabase.from("physiology_likelihoods").select("*", { count: "exact", head: true });

    const validation = {
      physiological_states: statesCount,
      symptom_physiology_map: symPhysioCount,
      physiology_diagnosis_map: physioDxCount,
      physiology_likelihoods: physioLikCount,
    };
    addLog(`  Physiological states: ${statesCount}`);
    addLog(`  Symptom-physiology links: ${symPhysioCount}`);
    addLog(`  Physiology-disease links: ${physioDxCount}`);
    addLog(`  Physiology likelihoods: ${physioLikCount}`);

    return new Response(JSON.stringify({ success: true, validation, log }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });

  } catch (err) {
    addLog(`FATAL ERROR: ${err.message}`);
    return new Response(JSON.stringify({ success: false, error: err.message, log }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
